### PR TITLE
edit-block-status

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Edit block status

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/301)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/301)* status: all files reviewed, 9 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/301#-NOxHd1l38KEVr2F_AcM:-NOxHd1l38KEVr2F_AcN:b6z16d7) ([raw file](https://github.com/saltastroops/web-manager/blob/f7f6219e7b1b89807123ae037d5727297e231c97/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html#L1)):*
> ```HTML
> <div *ngIf="isModalActive">
> ```

It seems the modal is not horizontally centred?
___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html` line 59 at r1](https://reviewable.io/reviews/saltastroops/web-manager/301#-NOxHNxi8mqjG400Szda:-NOxHNxi8mqjG400Szdb:ber8yb5) ([raw file](https://github.com/saltastroops/web-manager/blob/f7f6219e7b1b89807123ae037d5727297e231c97/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html#L59)):*
> ```HTML
>             <div *ngIf="error" class="invalid-feedback">
>               <div class="has-text-danger" data-test="error">
>                 {{ error }}
> ```

`error` is a very generic name... Maybe `submissionError` is a bit clearer?
___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html` line 63 at r1](https://reviewable.io/reviews/saltastroops/web-manager/301#-NOxGO5s5vr0BwLDDNih:-NOxGO5s5vr0BwLDDNii:b-tdp2c4) ([raw file](https://github.com/saltastroops/web-manager/blob/f7f6219e7b1b89807123ae037d5727297e231c97/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html#L63)):*
> ```HTML
>             </div>
>           </form>
>           <div class="modal-card-foot">
> ```

I think it is a bit odd that the submit button is outside the form.

You might consider occluding the whole modal content in the form:

```
<div *ngIf="isModalActive">
  <form>
  ...
  </form>
</div>
```

Yes that screws up the layout, but this can be fixed by setting the modal header width to 400px.

(And then you might handle via the form submission rather than a click handler,.
___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.ts` line 28 at r1](https://reviewable.io/reviews/saltastroops/web-manager/301#-NOxOpzw4kWwavRJZ13V:-NOxOq--DWPeOn0WGJBW:b-rrdjtu) ([raw file](https://github.com/saltastroops/web-manager/blob/f7f6219e7b1b89807123ae037d5727297e231c97/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.ts#L28)):*
> ```XML
>   loading = false;
>   editBlockStatusForm!: FormGroup;
>   submit = false;
> ```

You shouldn't need this variable -- can't you use the respective form property?
___
*[`src/app/proposal/blocks/block/priority-comment/priority-comment.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/301#-NOxQDOs0TdPoNjHV_Ex:-NOxQDOs0TdPoNjHV_Ey:br53rr8) ([raw file](https://github.com/saltastroops/web-manager/blob/f7f6219e7b1b89807123ae037d5727297e231c97/src/app/proposal/blocks/block/priority-comment/priority-comment.component.html#L1)):*
> ```HTML
> <div>
> ```

The name of this component is misleading, and I wonder whether this is indicative of an issue with how the components are structured? Maybe the overall structure (i.e. the table) should be included in the parent component, and the edit functionality should have its own component?

(This might be clear as mud, but then it might be easier to discuss this in a quick Zoom chat?)
___
*[`src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts` line 37 at r1](https://reviewable.io/reviews/saltastroops/web-manager/301#-NOxRC1r9bhAebGZmhD5:-NOxRC1r9bhAebGZmhD6:bktzv6r) ([raw file](https://github.com/saltastroops/web-manager/blob/f7f6219e7b1b89807123ae037d5727297e231c97/src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts#L37)):*
> ```XML
>   }
> 
>   isUserPrincipalContact(): boolean {
> ```

This looks like a method that should be in a utility file (`util.ts` or `utils.ts` -- we should combine these two some time...), so that it can be reused.
___
*[`src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts` line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager/301#-NOxRaa_4rqFfPu6EP5u:-NOxRaa_4rqFfPu6EP5v:bktzv6r) ([raw file](https://github.com/saltastroops/web-manager/blob/f7f6219e7b1b89807123ae037d5727297e231c97/src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts#L44)):*
> ```XML
>   }
> 
>   isUserPrincipalInvestigator(): boolean {
> ```

This looks like a method that should be in a utility file (`util.ts` or `utils.ts` -- we should combine these two some time...), so that it can be reused.
___
*[`src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts` line 53 at r1](https://reviewable.io/reviews/saltastroops/web-manager/301#-NOxS1P4-FpAx3Elx0PL:-NOxS1P4-FpAx3Elx0PM:bjbcb4i) ([raw file](https://github.com/saltastroops/web-manager/blob/f7f6219e7b1b89807123ae037d5727297e231c97/src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts#L53)):*
> ```XML
> 
> interface BlockStatusUpdate {
>   blockId: number;
> ```

Do you really need the `blockId` here?
___
*[`src/app/service/real/real-block.service.ts` line 33 at r1](https://reviewable.io/reviews/saltastroops/web-manager/301#-NOxSIYb2ja1B1jNJDmC:-NOxSIYc6_3MGAomPVXU:b-sup4jn) ([raw file](https://github.com/saltastroops/web-manager/blob/f7f6219e7b1b89807123ae037d5727297e231c97/src/app/service/real/real-block.service.ts#L33)):*
> ```XML
> 
>   /**
>    * Update a block statyus from the API server.
> ```

Status > status

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/301)* status: all files reviewed, 5 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/utils.ts` line 296 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPM3qwfBsio_5NOtXj_:-NPM3qwfBsio_5NOtXja:bqzhcht) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/utils.ts#L296)):*
> ```XML
> }
> 
> export function isUserPrincipalInvestigatorOrContact(
> ```

Give that you only check for one role at a time, maybe rather split up he function. `isUserPrincipalInvestigatorOrContact` IMHO suggests that the function checks for both roles.

(Also, wouldn't `role` have a type like `"Principal Investigator" | "Principal Contact"?)
___
*[`src/app/utils.ts` line 304 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPM6DHM4Y6c028U-aY7:-NPM6DHM4Y6c028U-aY8:b-5f05we) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/utils.ts#L304)):*
> ```XML
> 
>   if (role == "Principal Investigator") {
>     investigator = investigators.find((i) => i.id == user.id && i.isPi);
> ```

You could use `some` rather than `find`...
___
*[`src/app/proposal/blocks/block/block.component.ts` line 40 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPM6qQv5b85ZwpWe9lR:-NPM6qQv5b85ZwpWe9lS:bcozgsx) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/block.component.ts#L40)):*
> ```XML
>     this.validFrom = jd.start;
>     this.validUntil = jd.end;
>     this.authService.getUser().subscribe((user) => {
> ```

It seems you are not unsubscribing...
___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html` line 46 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPMKiqECTr9WPgHI73u:-NPMKiqFC_r9Mx09O1df:b-r9juoy) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html#L46)):*
> ```HTML
>             </div>
>           </div>
>           <div class="form-group input-section">
> ```

Maybe there is a bit much empty space between the dropdown and the block status reason label below it?

On a similar note, maybe the top and (more so) the bottom padding of the card body might have to be decreased a bit?
___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.ts` line 20 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPMMLkd0BH0g70TGWMA:-NPMMLkd0BH0g70TGWMB:bu5lnef) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.ts#L20)):*
> ```XML
>   @Output() blockStatusUpdate = new EventEmitter<{
>     blockId: number;
>     value: BlockStatusValue;
> ```

Wouldn't "status" be a bit clearer?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/301)* status: all files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[`src/app/utils.ts` line 296 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPM3qwfBsio_5NOtXj_:-NPMR4HoELif7HPNbxLn:bkdlmpt) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/utils.ts#L296)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Give that you only check for one role at a time, maybe rather split up he function. `isUserPrincipalInvestigatorOrContact` IMHO suggests that the function checks for both roles.

(Also, wouldn't `role` have a type like `"Principal Investigator" | "Principal Contact"?)
</blockquote></details>

I agree with you, as such I have split the two functions – the `role` parameter is no longer needed.
___
*[`src/app/utils.ts` line 304 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPM6DHM4Y6c028U-aY7:-NPMR0js9KatlnpqIuw1:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/utils.ts#L304)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could use `some` rather than `find`...
</blockquote></details>

Done.
___
*[`src/app/proposal/blocks/block/block.component.ts` line 40 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPM6qQv5b85ZwpWe9lR:-NPMQ8Xt93naYHmMRLR3:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/block.component.ts#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It seems you are not unsubscribing...
</blockquote></details>

Done.
___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html` line 46 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPMKiqECTr9WPgHI73u:-NPMQ3ER3rIbd9cxik-w:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.html#L46)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe there is a bit much empty space between the dropdown and the block status reason label below it?

On a similar note, maybe the top and (more so) the bottom padding of the card body might have to be decreased a bit?
</blockquote></details>

Done.
___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.ts` line 20 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPMMLkd0BH0g70TGWMA:-NPMOBDd5UxC85DqJU9x:b-40z0o5) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't "status" be a bit clearer?
</blockquote></details>

It would be in general but in this case, I am using an interface that extends a BlockStatus interface as shown in the code snippet below.



_Code snippet:_
```XML
interface BlockStatusUpdate extends BlockStatus {
  blockId: number;
}
```

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/301)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block/block.component.html` line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPMuBD8Ch0hHr7aaSbV:-NPMuBD8Ch0hHr7aaSbW:bjszkqu) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/block.component.html#L25)):*
> ```HTML
>             <th>Priority</th>
>             <th>Comments</th>
>             <th *ngIf="showEditBlockButton">Edit</th>
> ```

While this is not for this PR, here is a suggestion:

The you have a banner or similar for showing the block status, that might be a good place where to have the button for editing it.

The banner probably should also should the status reason, if there is one.
___
*[`src/app/proposal/blocks/block/block.component.ts` line 40 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPM6qQv5b85ZwpWe9lR:-NPMtlTA9M8VauhgeCh2:bocxtk7) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/block.component.ts#L40)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the change?
___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.scss` line 9 at r3](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPMwoS-D1vGlcYslRkV:-NPMwoS-D1vGlcYslRkW:bl04tl1) ([raw file](https://github.com/saltastroops/web-manager/blob/a0a18b55d6d464cc451a1295077aaa8955b45f02/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.scss#L9)):*
> ```SCSS
> .input-section {
>   width: 300px;
>   height: 90px;
> ```

Setting an explicit height here (and elsewhere in this stylesheet) looks a bit like a hack to me. The better option might be to use paddings and/or margins?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/301)* status: 10 of 25 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/blocks/block/block.component.html` line 25 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPMuBD8Ch0hHr7aaSbV:-NPR4v8FDn_GOTdh-OIe:b4v6yaj) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/block.component.html#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

While this is not for this PR, here is a suggestion:

The you have a banner or similar for showing the block status, that might be a good place where to have the button for editing it.

The banner probably should also should the status reason, if there is one.
</blockquote></details>

You're right, i will add this suggestions on another PR.
___
*[`src/app/proposal/blocks/block/block.component.ts` line 40 at r2](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPM6qQv5b85ZwpWe9lR:-NPRRxDND_6V3SCIsMMv:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/d0fbbc353418fc5b1c1c4075dafb812495294269/src/app/proposal/blocks/block/block.component.ts#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't see the change?
</blockquote></details>

Done.
___
*[`src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.scss` line 9 at r3](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPMwoS-D1vGlcYslRkV:-NPR3JMBEJBJZzdsuzaP:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/a0a18b55d6d464cc451a1295077aaa8955b45f02/src/app/proposal/blocks/block/edit-block-status-modal/edit-block-status-modal.component.scss#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Setting an explicit height here (and elsewhere in this stylesheet) looks a bit like a hack to me. The better option might be to use paddings and/or margins?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/301)* status: all files reviewed, 7 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/e2e/proposal/block-status.cy.ts` line 33 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWGWTJ320LPoh7JWzE:-NPWGWTJ320LPoh7JWzF:bu1ncbc) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L33)):*
> ```XML
> 
>   it("should show edit block status modal", () => {
>     BlockSummaries.clickBlockNameLink(0);
> ```

You might also want to check that the modal is not shown before you click on the button.
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 41 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWGuUvEOvsOebEfU1z:-NPWGuUvEOvsOebEfU2-:b-7pe7s0) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L41)):*
> ```XML
>     BlockSummaries.clickBlockNameLink(1);
>     Block.clickEditBlockStatusButton();
>     Block.editBlockStatusModalShown(true);
> ```

You test this already elsewhere,
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 50 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWH-UW57CzUypOoaLy:-NPWH-UW57CzUypOoaLz:b-7pe7s0) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L50)):*
> ```XML
>     BlockSummaries.clickBlockNameLink(2);
>     Block.clickEditBlockStatusButton();
>     Block.editBlockStatusModalShown(true);
> ```

You test this already elsewhere,
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 84 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWHfCw26aMJu10_FAS:-NPWHfCw26aMJu10_FAT:b-zhavvl) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L84)):*
> ```XML
>   });
> 
>   it("should not show a button for editing block status for a SA", () => {
> ```

Why should it not show the button for SAs?
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 118 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWIOgPERcDbxZ_Uw17:-NPWIOgPERcDbxZ_Uw18:b-gf6sp2) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L118)):*
> ```XML
>   });
> 
>   it("should allow update the block status for a PI", () => {
> ```

update > updating
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 119 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWI-UB1zOgeFae0UiN:-NPWI-UB1zOgeFae0UiO:bmjb7j1) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L119)):*
> ```XML
> 
>   it("should allow update the block status for a PI", () => {
>     BlockSummaries.clickBlockNameLink(-1);
> ```

This looks suspiciously like a test you did above already? Thus isn't it enough to check that you see the button?
___
*[`cypress/support/components/block.ts` line 39 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPX4q-4DtA0JIIFeqbi:-NPX4q-4DtA0JIIFeqbj:b-l03sf8) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/support/components/block.ts#L39)):*
> ```XML
> 
>   static blockStatusUpdatedWithStatus(status: string): void {
>     cy.get(BLOCK_STATUS).invoke("text").should("contain", status.trim());
> ```

I don't think there is a need for the `.invoke("text")`. (The tests seem to pass without.)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/301)* status: 23 of 25 files reviewed, 7 unresolved discussions (waiting on @hettlage)

___
*[`cypress/e2e/proposal/block-status.cy.ts` line 33 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWGWTJ320LPoh7JWzE:-NPXWGrWCa5MRWVwkAvc:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might also want to check that the modal is not shown before you click on the button.
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 41 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWGuUvEOvsOebEfU1z:-NPXWki29WL2xoepcdV1:bss4a2b) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You test this already elsewhere,
</blockquote></details>

Removed.
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 50 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWH-UW57CzUypOoaLy:-NPXa94_DogGzhoTRuFm:bss4a2b) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You test this already elsewhere,
</blockquote></details>

Removed.
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 84 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWHfCw26aMJu10_FAS:-NPXWozC0kLcvyyrUag7:b-nuac0l) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L84)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why should it not show the button for SAs?
</blockquote></details>

My mistake, and because of the async nature of cypress the test was passing when it should be failing. I have fixed it now.
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 118 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWIOgPERcDbxZ_Uw17:-NPXXlyd09vQpjcpBNPp:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L118)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

update > updating
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/block-status.cy.ts` line 119 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPWI-UB1zOgeFae0UiN:-NPXXSvT1B3dqJhWcGzs:bz9vupj) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/e2e/proposal/block-status.cy.ts#L119)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This looks suspiciously like a test you did above already? Thus isn't it enough to check that you see the button?
</blockquote></details>

You're right, I have updated it now.
___
*[`cypress/support/components/block.ts` line 39 at r4](https://reviewable.io/reviews/saltastroops/web-manager/301#-NPX4q-4DtA0JIIFeqbi:-NPXa6O9D1yrNxOB67bl:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/1d40f957eb8ad1daffac9336e68d5e246f1394fe/cypress/support/components/block.ts#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think there is a need for the `.invoke("text")`. (The tests seem to pass without.)
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/301)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
