### PR TITLE
Invesigator's proposal approval button functionality

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)

### CODE REVIEW

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: all files reviewed, 10 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/investigators/investigators.component.html` line 50 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAkvmE9UB_Kf5imP41:-NQB8Y5a2Jkjn3HG69KV:bnaho46) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/proposal/investigators/investigators.component.html#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is there a reason why you are using a `ng-template` here?
</blockquote></details>

No, this is how it was implemented previously. I have updated this now.
___
*[`src/app/proposal/investigators/investigators.component.html` line 54 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAlgJC6UEV7JOOrgFC:-NQB5hij69cc4iKhYg95:bro58jv) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/proposal/investigators/investigators.component.html#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't you duplicating code here?
</blockquote></details>

I was, I have updated this.
___
*[`src/app/proposal/investigators/investigators.component.ts` line 27 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAma-51YUdXYJkwluE:-NQB5wOp3HuW0EofST9g:b-bhs04w) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/proposal/investigators/investigators.component.ts#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You never unsubscribe, do you? :-)
</blockquote></details>

I am now.
___
*[`src/app/proposal/investigators/investigators.component.ts` line 37 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAn9s-D_khWPsk9Zlo:-NQB6FY707FNETGd8zcK:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/proposal/investigators/investigators.component.ts#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"id" is a very generic name, and it might be worth using a more specific name, such as investigatorId.
</blockquote></details>

Done.
___
*[`src/app/proposal/investigators/investigators.component.ts` line 47 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAoWOHA8GxPcqTrDEm:-NQB6O4V9sopCtxZhcj6:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/proposal/investigators/investigators.component.ts#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better just "investigatorDetails"?
</blockquote></details>

Done.
___
*[`src/app/proposal/investigators/investigators.component.ts` line 52 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAolDZ2Nbzot7Lp26m:-NQB6SC--YuS8wJ2u4e6:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/proposal/investigators/investigators.component.ts#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't you remove the class even if `userInvestigatorDetails` is undefined?
</blockquote></details>

Done.
___
*[`src/app/proposal/investigators/investigators.component.ts` line 53 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAp3Vx0wHKfY8GLwzG:-NQB6wTT0_BqhTiANgk6:bss4a2b) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/proposal/investigators/investigators.component.ts#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need an alert if the update is successful.
</blockquote></details>

Removed.
___
*[`src/app/service/proposal.service.ts` line 72 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAwdi68rVAzU0rSoe2:-NQB7Jna5RKkDFtpQVqf:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/service/proposal.service.ts#L72)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add your docstring from the implementation here as well? -

```
/**
   * Submit an investigator's proposal approval status to the API server.
   */
```
</blockquote></details>

Done.
___
*[`src/app/service/proposal.service.ts` line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAq4Jt3PQPBgT7K56Q:-NQB8SGe3yM87tLFZTkt:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/service/proposal.service.ts#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be "investigatorId"?
</blockquote></details>

Done.
___
*[`src/app/service/real/real-proposal.service.ts` line 181 at r2](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQAwYvlA0CI1iEBS5Kz:-NQB8T3V7LYOct6NVSOC:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/cc149512cdba7b79e0352031798198002575cbb3/src/app/service/real/real-proposal.service.ts#L181)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that be "investigatorId"?
</blockquote></details>

Done.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/investigators/investigators.component.html` line 56 at r3](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQBer6x-sMd4HLCqeZw:-NQOsjfY2kdeqzhL9vqt:b-hbhz0c) ([raw file](https://github.com/saltastroops/web-manager/blob/ee844d18d10def0f776efab81bdcdcbc4d7fd84d/src/app/proposal/investigators/investigators.component.html#L56)):*
>> Is this really false?
Yes, it is. Approve values if false when the investigator rejects the proposal.

I have updated the template accordingly.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/investigators/investigators.component.html` line 51 at r4](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQUVhTe8mZRnT89iGjv:-NQUVhTe8mZRnT89iGjw:b-yjctc0) ([raw file](https://github.com/saltastroops/web-manager/blob/dab060c33ab8058beb5871321bd9e7f3b4f4dafd/src/app/proposal/investigators/investigators.component.html#L51)):*
> ```HTML
>       <td>{{ i.affiliation.department }}</td>
>       <td *ngIf="showApprovalStatusButton">
>         <div *ngIf="!i.hasApprovedProposal">
> ```

I would suggest to have the buttons next to each other horizontally rather than vertically.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/investigators/investigators.component.html` line 51 at r4](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQUVhTe8mZRnT89iGjv:-NQUslsO4-ilV_tinXlH:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/dab060c33ab8058beb5871321bd9e7f3b4f4dafd/src/app/proposal/investigators/investigators.component.html#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to have the buttons next to each other horizontally rather than vertically.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/investigators/investigators.component.html` line 52 at r5](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQ_wWHS6b7ZW_pG7B0H:-NQ_wWHS6b7ZW_pG7B0I:b-xt62ly) ([raw file](https://github.com/saltastroops/web-manager/blob/663c6c531fdcc77f46e3fc72b7ed6138d88f0d75/src/app/proposal/investigators/investigators.component.html#L52)):*
> ```HTML
>       <td
>         *ngIf="showApprovalStatusButton"
>         [ngClass]="{ 'null-approval-status': i.hasApprovedProposal === null }"
> ```

The border line is positioned incorrectly.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: 7 of 19 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/investigators/investigators.component.html` line 52 at r5](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQ_wWHS6b7ZW_pG7B0H:-NQetLBp2BUhrBby2cYZ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/663c6c531fdcc77f46e3fc72b7ed6138d88f0d75/src/app/proposal/investigators/investigators.component.html#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The border line is positioned incorrectly.
</blockquote></details>

Done.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: all files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`cypress/e2e/proposal/investigators.cy.ts` line 13 at r6](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQf3OGd3Dcj918PYyEX:-NQiuJQ_2BQuAUHvshL7:b-pbdqz3) ([raw file](https://github.com/saltastroops/web-manager/blob/87318396efe53a5a415ee94ae57bb5ae90c7b429/cypress/e2e/proposal/investigators.cy.ts#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We really have to decide whether to get rid of recording... :-/
</blockquote></details>

Agreed.
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 19 at r6](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQf3Wqz66zKJlHZXE6l:-NQiu_gCCPwZtzbtvSV_:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/87318396efe53a5a415ee94ae57bb5ae90c7b429/cypress/e2e/proposal/investigators.cy.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be an empty line here.
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 21 at r6](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQf7tSr5sfA0Y_m-cDl:-NQjAGTgBuM_wNo3SBuI:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/87318396efe53a5a415ee94ae57bb5ae90c7b429/cypress/e2e/proposal/investigators.cy.ts#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Better perhaps: When I login as the PI

Wouldn't it make more sense to perform the test for a normal (i.e. non-PI, non-PC) user?

</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 31 at r6](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQf83XB5p8hiBNVKFNQ:-NQjAG1K2Ycqn4Sp0A9M:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/87318396efe53a5a415ee94ae57bb5ae90c7b429/cypress/e2e/proposal/investigators.cy.ts#L31)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should test that an investigator can only see the button(s) for themselves, not for other investigators.
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 40 at r6](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQf8lzO5gHVvXC7lVlK:-NQjATLK49jYz7rM0gX3:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/87318396efe53a5a415ee94ae57bb5ae90c7b429/cypress/e2e/proposal/investigators.cy.ts#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

non-investigators > administrators  ?
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 51 at r6](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQf8zI9A_LlvrcScBUx:-NQjAU5L-YsLVgmcVcVm:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/87318396efe53a5a415ee94ae57bb5ae90c7b429/cypress/e2e/proposal/investigators.cy.ts#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There should be an empty line here.
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 53 at r6](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQf93QmEdyiwyZ95K5Y:-NQjAVTS1SdQg2tGJomH:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/87318396efe53a5a415ee94ae57bb5ae90c7b429/cypress/e2e/proposal/investigators.cy.ts#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

When I login as an administrator
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 63 at r6](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQf9I9_9E52j9t257N8:-NQjD8FE1BgKbKLGhNUL:b-g6z25j) ([raw file](https://github.com/saltastroops/web-manager/blob/87318396efe53a5a415ee94ae57bb5ae90c7b429/cypress/e2e/proposal/investigators.cy.ts#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That's puzzling. Isn't the user an administrator and should see the buttons?!
</blockquote></details>

It was a bug, probably the case of copy and paste. It is now fixed.
___
*[`cypress/support/components/investigators.ts` line 36 at r6](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQf8P7m2cNLaBPSHQlX:-NQjD6ON3SrEbC1s_vto:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/87318396efe53a5a415ee94ae57bb5ae90c7b429/cypress/support/components/investigators.ts#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't that the same as "be.visible"?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/e2e/proposal/investigators.cy.ts` line 10 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjqQF_CXMwrsFz-a5e:-NQjqQF_CXMwrsFz-a5f:b-us4j4h) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/e2e/proposal/investigators.cy.ts#L10)):*
> ```XML
> describe("Investigators", () => {
>   // TODO use correct method for getting the username
>   const USERNAME = "rajeev"; // getEnvVariable("piUsername");
> ```

I guess this should be reverted?
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 51 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjqm-RDu14h9AVUjLi:-NQjqm-RDu14h9AVUjLj:b-55433b) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/e2e/proposal/investigators.cy.ts#L51)):*
> ```XML
>     Investigators.clickApprovalButton(3);
>     Investigators.approvalStatusReasonUpdatedWithStatus(3, "Reject");
>     cy.wait(1500);
> ```

Why do you need this wait?
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 94 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjr-No13gENmygJ9wA:-NQjr-No13gENmygJ9wB:b-55433b) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/e2e/proposal/investigators.cy.ts#L94)):*
> ```XML
>     Investigators.clickApprovalButton(0);
>     Investigators.approvalStatusReasonUpdatedWithStatus(0, "Reject");
>     cy.wait(1500);
> ```

Why do you need this wait?
___
*[`cypress/support/components/investigators.ts` line 11 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjrNDK5auk2kSb0GJz:-NQjrNDK5auk2kSb0GK-:b68ln05) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/support/components/investigators.ts#L11)):*
> ```XML
>   }
> 
>   static approvalStatusReasonUpdatedWithStatus(
> ```

Do you really mean "Reason" rather than "Button"?
___
*[`src/app/proposal/investigators/investigators.component.html` line 61 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjt1uA8na8PtRSoLPS:-NQjt1uB7GZ1JlG-B4bq:b-rjvl5f) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/src/app/proposal/investigators/investigators.component.html#L61)):*
> ```HTML
>               class="button is-success is-small"
>               [ngClass]="{
>                 'is-hidden': !(i.id === user.id || isAdministrator(user))
> ```

It might make slightly more sense to use an `ng-container containing both button, with the `*ngIf` condition ` 
___
*[`src/app/proposal/investigators/investigators.component.html` line 75 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjwdZIDQuL9NUTxq_g:-NQjwdZIDQuL9NUTxq_h:bu6xv6u) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/src/app/proposal/investigators/investigators.component.html#L75)):*
> ```HTML
>               class="button is-danger is-small"
>               [ngClass]="{
>                 'is-hidden': !(i.id === user.id || isAdministrator(user))
> ```

See previous comment.



_Code quote:_
```HTML
!(i.id === user.id || isAdministrator(user)
```

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: 17 of 19 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`cypress/e2e/proposal/investigators.cy.ts` line 10 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjqQF_CXMwrsFz-a5e:-NQxQdbP0J7oawGzRGF2:b-lncakk) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/e2e/proposal/investigators.cy.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I guess this should be reverted?
</blockquote></details>

Yes, it will be. The problem I am having is that `getEnvVariable("piUsername")` returns the PI username from the `salt-testdata` repository, and the username is currently set to "kevin". And this user seems to be mostly associated with GWE proposals, which only show the investigator "Gravitational Wave Proposals" in the list of investigators (is this expected?). This implies no tests because "kevin" is not on the list of investigators. As a result, I hard-coded the username and added a to-do as a reminder to attend to it.
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 51 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjqm-RDu14h9AVUjLi:-NQxV1It-SXySD9e3KjZ:beij89z) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/e2e/proposal/investigators.cy.ts#L51)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need this wait?
</blockquote></details>

Cypress happens to click the buttons at the "same time" and as such, the test fails because the second request does not happen.
___
*[`cypress/e2e/proposal/investigators.cy.ts` line 94 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjr-No13gENmygJ9wA:-NQxVrEr19Q9AQlbYqGM:beij89z) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/e2e/proposal/investigators.cy.ts#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need this wait?
</blockquote></details>

Cypress happens to click the buttons at the "same time" and as such, the test fails because the second request does not happen.
___
*[`cypress/support/components/investigators.ts` line 11 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjrNDK5auk2kSb0GJz:-NQxXuWqD2MJQdVadNuh:buc0km9) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/support/components/investigators.ts#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you really mean "Reason" rather than "Button"?
</blockquote></details>

I meant "button". Thanks for spotting this.
___
*[`src/app/proposal/investigators/investigators.component.html` line 61 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjt1uA8na8PtRSoLPS:-NQxWjsKAtwFJBjDpAIZ:b-wue1yz) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/src/app/proposal/investigators/investigators.component.html#L61)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might make slightly more sense to use an `ng-container containing both button, with the `*ngIf` condition ` 
</blockquote></details>

In principle, I agree with you. However, that way if the condition is not met, the button is "removed" from the DOM which makes it challenging to test that an investigator can only update the status for themselves, not for other investigators. 

Maybe we should discuss this.
___
*[`src/app/proposal/investigators/investigators.component.html` line 75 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjwdZIDQuL9NUTxq_g:-NQxYkzlBHBf_BlsxwWv:b-hxj1hk) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/src/app/proposal/investigators/investigators.component.html#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See previous comment.
</blockquote></details>

Maybe we should discuss this.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`cypress/e2e/proposal/investigators.cy.ts` line 10 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjqQF_CXMwrsFz-a5e:-NQyVduK01rLnYHr8aMb:b-yruiuf) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/e2e/proposal/investigators.cy.ts#L10)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Yes, it will be. The problem I am having is that `getEnvVariable("piUsername")` returns the PI username from the `salt-testdata` repository, and the username is currently set to "kevin". And this user seems to be mostly associated with GWE proposals, which only show the investigator "Gravitational Wave Proposals" in the list of investigators (is this expected?). This implies no tests because "kevin" is not on the list of investigators. As a result, I hard-coded the username and added a to-do as a reminder to attend to it.
</blockquote></details>

Now I'm a bit puzzled... I thought you wanted tonnes an investigator (not PI) here?
___
*[`cypress/support/components/investigators.ts` line 11 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjrNDK5auk2kSb0GJz:-NQyW3qC7WgYeTKj1GA6:by2jj05) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/support/components/investigators.ts#L11)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I meant "button". Thanks for spotting this.
</blockquote></details>

Again I'm puzzled. You say you meant "Button", but you haven't included "Button".

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/313)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`cypress/e2e/proposal/investigators.cy.ts` line 10 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjqQF_CXMwrsFz-a5e:-NQyXNve8Oi4E5BLMa2Z:b-bjfveu) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/e2e/proposal/investigators.cy.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Now I'm a bit puzzled... I thought you wanted tonnes an investigator (not PI) here?
</blockquote></details>

My mistake, i forgot to implement it. Done now.
___
*[`cypress/support/components/investigators.ts` line 11 at r7](https://reviewable.io/reviews/saltastroops/web-manager/313#-NQjrNDK5auk2kSb0GJz:-NQyXUZpAwPG-reuGhAy:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/8789a3855699cdf13b22f7f973609e5b60a0bd2f/cypress/support/components/investigators.ts#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Again I'm puzzled. You say you meant "Button", but you haven't included "Button".
</blockquote></details>

Done.

**Pull request merged**
