### PR TITLE
show-pi-and-pc

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Show PI and PC on general info table

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/283)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/283)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/proposal.component.html` line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager/283#-NNakMjMDYl2pTnul2HW:-NNakMjMDYl2pTnul2HX:bmje9my) ([raw file](https://github.com/saltastroops/web-manager/blob/fadd77e9485204f9b20f493d539a113642a322cc/src/app/proposal/proposal.component.html#L10)):*
> ```HTML
>   <hr class="heading-line proposal-header" />
>   <div class="block">
>     <wm-general-proposal-info
> ```

You now pass five parameters... Wouldn't it make sense to just pass the proposal p instead?
___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 24 at r1](https://reviewable.io/reviews/saltastroops/web-manager/283#-NNal6jb1n6Ppp-Eg78A:-NNal6jb1n6Ppp-Eg78B:b-fm77gs) ([raw file](https://github.com/saltastroops/web-manager/blob/fadd77e9485204f9b20f493d539a113642a322cc/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L24)):*
> ```XML
>   statusDescription = "";
>   backgroundColor = "";
>   PI!: Investigator;
> ```

Variable names should not start with a capital. Maybe rather spell the names out, principalInvestigatir and principalContact?
___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 33 at r1](https://reviewable.io/reviews/saltastroops/web-manager/283#-NNakqsCDXacNgwQwKue:-NNakqsCDXacNgwQwKuf:borjbzx) ([raw file](https://github.com/saltastroops/web-manager/blob/fadd77e9485204f9b20f493d539a113642a322cc/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L33)):*
> ```XML
>     this.firstSubmission = parseISO(this.generalProposalInfo.firstSubmission);
>     this.semesterControl.setValue(this.currentSemester);
>     const pcIndex = this.investigators.findIndex(
> ```

Simpler: Use the `find` method.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/283)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/proposal.component.html` line 10 at r1](https://reviewable.io/reviews/saltastroops/web-manager/283#-NNakMjMDYl2pTnul2HW:-NNebdciEt1NPPcIuhCe:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fadd77e9485204f9b20f493d539a113642a322cc/src/app/proposal/proposal.component.html#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You now pass five parameters... Wouldn't it make sense to just pass the proposal p instead?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 24 at r1](https://reviewable.io/reviews/saltastroops/web-manager/283#-NNal6jb1n6Ppp-Eg78A:-NNeZy_LEfg-nd-m6gny:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fadd77e9485204f9b20f493d539a113642a322cc/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Variable names should not start with a capital. Maybe rather spell the names out, principalInvestigatir and principalContact?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 33 at r1](https://reviewable.io/reviews/saltastroops/web-manager/283#-NNakqsCDXacNgwQwKue:-NNeZxdVE07k0IwNa6vX:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fadd77e9485204f9b20f493d539a113642a322cc/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L33)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Simpler: Use the `find` method.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/283)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 20 at r2](https://reviewable.io/reviews/saltastroops/web-manager/283#-NNgEJhw29vKy9xAnKee:-NNgEJhx26smWB6PYEkt:b-gsz03v) ([raw file](https://github.com/saltastroops/web-manager/blob/f68f872eb4f57e8e8efa237128a221ac9489d811/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L20)):*
> ```XML
>   statusDescription = "";
>   backgroundColor = "";
>   proposalInvestigator: Investigator | undefined;
> ```

proposalInvestigator > principalInvestigator

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/283)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts` line 20 at r2](https://reviewable.io/reviews/saltastroops/web-manager/283#-NNgEJhw29vKy9xAnKee:-NNgFMdT1J-tRHtOjqp9:bgei7ep) ([raw file](https://github.com/saltastroops/web-manager/blob/f68f872eb4f57e8e8efa237128a221ac9489d811/src/app/proposal/general/general-proposal-info/general-proposal-info.component.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

proposalInvestigator > principalInvestigator
</blockquote></details>

Oh yes... Thanks!

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/283)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
