### PR TITLE
home-page-content

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Home page content forn unauthorized users

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/218)

### CODE REVIEW

**Review by hettlage — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/218)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Review by hettlage — COMMENTED** [review]
This one's over to you, as I made changes.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/218#-:-NMFkrK-2-x479k8nopJ:b-v5wv7k)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Review by mofokeng-chaka — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/218#-:-NMSPIv50tVbROWTXdF9:bg7igk9)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @hettlage)

**Review by mofokeng-chaka — COMMENTED** [review]
I have a few minor updates coming your way as well.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/218#-:-NMSPNU2-XEy24pAUqWy:b7tysvp)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @hettlage)

**Review by mofokeng-chaka — COMMENTED** [review]
I just pushed the above-mentioned changes, it is back to you.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/218#-:-NMSQFFGDZY0869tNXbp:b86kszy)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @hettlage)

**Comment by mofokeng-chaka** [comment]
> Shouldn't this be SALT? And do we really need the copyright...?

I think you are right, it should be SALT. We don't really need it since the content is automatically protected by copyright, but I think it makes no harm either and also a good practice to put the notice on the website.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/218)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

**Pull request merged**
