### PR TITLE
block-background-color-updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Block summary background color updates

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/287)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/287)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.ts` line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager/287#-NNkltsUCJpJnBTyl2er:-NNkltsUCJpJnBTyl2es:bbej6ae) ([raw file](https://github.com/saltastroops/web-manager/blob/1266e339ed2fc24415584cd4889b767075ba9112/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L97)):*
> ```XML
>   blockClass(block: BlockSummary): string {
>     if (this.isCompleted(block)) {
>       return "";
> ```

I would think that "normal" blocks should have no background, and I would consider non-completed blocks normal. So I think Encarni's second option (a light gray background) is the better one. This might be further reinforced by making the text colour slightly lighter as well, as long as it does not impact readability.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/287)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.ts` line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager/287#-NNkltsUCJpJnBTyl2er:-NOUE-uE5K8PgDD0Umss:bcs4vf8) ([raw file](https://github.com/saltastroops/web-manager/blob/1266e339ed2fc24415584cd4889b767075ba9112/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L97)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But now you've chucked out any background for completed blocks...

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/287)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.ts` line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager/287#-NNkltsUCJpJnBTyl2er:-NOi60JfD--XpeGwjf8m:b-4yiko9) ([raw file](https://github.com/saltastroops/web-manager/blob/1266e339ed2fc24415584cd4889b767075ba9112/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But now you've chucked out any background for completed blocks...
</blockquote></details>

It is now added back.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/287)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.ts` line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager/287#-NNkltsUCJpJnBTyl2er:-NOiAQVx3fSJjJGjK0ko:bbqilda) ([raw file](https://github.com/saltastroops/web-manager/blob/1266e339ed2fc24415584cd4889b767075ba9112/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L97)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

It is now added back.
</blockquote></details>

But now normal and completed blocks have the same background colour...

How about using something like the following styles for the completed blocks (and none for the normal blocks):

```
.completed-block {
  background-color: #f5f5f5;
  color: #999996;
}
```

Then the weather icons should be lighter for completed blocks as well. The easiest way to achieve this might be to have two different svg files for each of the icons.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/287)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.ts` line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager/287#-NNkltsUCJpJnBTyl2er:-NOiQRVG0TUCLeBvrm7_:b8zhnjo) ([raw file](https://github.com/saltastroops/web-manager/blob/1266e339ed2fc24415584cd4889b767075ba9112/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But now normal and completed blocks have the same background colour...

How about using something like the following styles for the completed blocks (and none for the normal blocks):

```
.completed-block {
  background-color: #f5f5f5;
  color: #999996;
}
```

Then the weather icons should be lighter for completed blocks as well. The easiest way to achieve this might be to have two different svg files for each of the icons.

</blockquote></details>

I have added the new style for the completed block.

Regarding icons, could you help with them? Where do I get such icons?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/287)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.ts` line 97 at r1](https://reviewable.io/reviews/saltastroops/web-manager/287#-NNkltsUCJpJnBTyl2er:-NOmp1-T--TJilWusFsL:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/1266e339ed2fc24415584cd4889b767075ba9112/src/app/proposal/blocks/block-summaries/block-summaries.component.ts#L97)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The icons are in the `assets/icons` folder. You just have to copy the relevant icons and change the properties for setting the colour (probably just the `fill` attribute on the svg tag). 
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/287)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
