### PR TITLE
Migrate to Cypress 10

### PR DESCRIPTION
**Pull request by hettlage**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/137)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/137)* status: all files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`cypress/support/utils.ts` line 211 at r1](https://reviewable.io/reviews/saltastroops/web-manager/137#-N9fF0IzAsjXueSPVdnO:-N9fF0IzAsjXueSPVdnP:b-b8269f) ([raw file](https://github.com/saltastroops/web-manager/blob/2b770f81cf1ec8be95ca3cbb58f0818fb2ae32bd/cypress/support/utils.ts#L211)):*
> ```XML
>  */
> export function getApiUrl(): string {
>   const apiUrl = Cypress.env("apiUrl") || null;
> ```

Cypress.env >>> getEnvVariable ?



_Code quote:_
```XML
getEnvVariable
```
___
*[`cypress/support/e2e.ts` line 46 at r1](https://reviewable.io/reviews/saltastroops/web-manager/137#-N9fEXRh64bZPMId4hn4:-N9fEXRuBM6yfFu5wVRW:b-rlhxk7) ([raw file](https://github.com/saltastroops/web-manager/blob/2b770f81cf1ec8be95ca3cbb58f0818fb2ae32bd/cypress/support/e2e.ts#L46)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-var-requires
> const registerCypressGrep = require("cypress-grep");
> registerCypressGrep();
> ```

Maybe this plugin is no longer necessary since we are not using it anywhere?
___
*[`cypress/support/e2e.ts` line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager/137#-N9f07gx4ODTUhIGwp2r:-N9f07gyEk-S6GqGQ-Ao:b-yj85v0) ([raw file](https://github.com/saltastroops/web-manager/blob/2b770f81cf1ec8be95ca3cbb58f0818fb2ae32bd/cypress/support/e2e.ts#L48)):*
> ```XML
> registerCypressGrep();
> 
> const recordHttpConfig = JSON.parse(Cypress.env("recordHttpConfig") || "{}");
> ```

As per our discussion in the previous PR, this line fails in my case. It only works when declared like this: `const recordHttpConfig = Cypress.env("recordHttpConfig") || {}`

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/137)* status: 12 of 16 files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/support/utils.ts` line 211 at r1](https://reviewable.io/reviews/saltastroops/web-manager/137#-N9fF0IzAsjXueSPVdnO:-N9fTHdK5MA9CcOC5On8:b-n4kr80) ([raw file](https://github.com/saltastroops/web-manager/blob/2b770f81cf1ec8be95ca3cbb58f0818fb2ae32bd/cypress/support/utils.ts#L211)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Cypress.env >>> getEnvVariable ?
</blockquote></details>

Updated. Thanks!
___
*[`cypress/support/e2e.ts` line 46 at r1](https://reviewable.io/reviews/saltastroops/web-manager/137#-N9fEXRh64bZPMId4hn4:-N9fTblj-brtzRbceFAS:bf7zv3s) ([raw file](https://github.com/saltastroops/web-manager/blob/2b770f81cf1ec8be95ca3cbb58f0818fb2ae32bd/cypress/support/e2e.ts#L46)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Maybe this plugin is no longer necessary since we are not using it anywhere?
</blockquote></details>

Removed. Thanks.
___
*[`cypress/support/e2e.ts` line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager/137#-N9f07gx4ODTUhIGwp2r:-N9fTOaM4AM7HAT92cDF:b-162o3r) ([raw file](https://github.com/saltastroops/web-manager/blob/2b770f81cf1ec8be95ca3cbb58f0818fb2ae32bd/cypress/support/e2e.ts#L48)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

As per our discussion in the previous PR, this line fails in my case. It only works when declared like this: `const recordHttpConfig = Cypress.env("recordHttpConfig") || {}`
</blockquote></details>

From all I can see, the line didn't change from `development` to this branch. Anyway, I've removed the `JSON.parse`.

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/137)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`cypress/support/e2e.ts` line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager/137#-N9f07gx4ODTUhIGwp2r:-N9fUBfFCQ6EztNpJ83N:bs3hul2) ([raw file](https://github.com/saltastroops/web-manager/blob/2b770f81cf1ec8be95ca3cbb58f0818fb2ae32bd/cypress/support/e2e.ts#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

From all I can see, the line didn't change from `development` to this branch. Anyway, I've removed the `JSON.parse`.
</blockquote></details>

Oh my mistake then, sorry.

**Review by mofokeng-chaka — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/137#-:-N9fUmUi7b5YqxKPTObj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Pull request merged**
