### PR TITLE
Fixing the phase 1 display

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/255)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/255)* status: all files reviewed (commit messages unreviewed), 11 unresolved discussions (waiting on @Eb-Zeero)

___
*[`package.json` line 30 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN8A1yK7t99GemYH-ra:-NN8A1yK7t99GemYH-rb:b-96r36) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/package.json#L30)):*
> ```JSON
>     "@testing-library/angular": "^10.8.1",
>     "bulma": "^0.9.2",
>     "bulma-accordion": "^2.0.1",
> ```

Should be removed, as discussed.
___
*[`src/app/proposal/proposal.component.html` line 25 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7UrIJ-UADDTRQ9yq0:-NN7UrIJ-UADDTRQ9yq1:b6yj1sy) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/proposal.component.html#L25)):*
> ```HTML
>     </div>
>     <div class="block">
>       <wm-requested-time
> ```

"wm-requested-time" (singular) and "requestedTimes" (plural;) is somewhat inconsistent.
___
*[`src/app/proposal/proposal.component.html` line 35 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7V0wIEBHk630TwNJV:-NN7V0wIEBHk630TwNJW:b-gcl31j) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/proposal.component.html#L35)):*
> ```HTML
>         [timeAllocations]="p.timeAllocations"
>       ></wm-charged-time>
>       <wm-time-allocation-table
> ```

"time-allocation-table" (singular) and timeAllocations (plural) is somewhat inconsistent.
___
*[`src/app/proposal/p1-details/p1-details.component.html` line 6 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN8CTItAkRugOi-Iw2p:-NN8CTItAkRugOi-Iw2q:b-543411) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/p1-details/p1-details.component.html#L6)):*
> ```HTML
>       [generalProposalInfo]="proposal.generalInfo"
>     ></wm-phase-one-proposal-details>
>     <wm-requested-time
> ```

The requested times table jumps when it is expanded.
___
*[`src/app/proposal/p1-details/p1-details.component.html` line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7VON76FVznj7Xdzq0:-NN7VON76FVznj7Xdzq1:b-mxg1rx) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/p1-details/p1-details.component.html#L12)):*
> ```HTML
> </div>
> <div class="block">
>   <wm-thesis-students
> ```

"thesis-students" sounds a bit odd to me, and the "thesis" is more important in the context of the proposal than the specific student. So maybe rather call this element "wm-student-theses"?
___
*[`src/app/proposal/requested-time/requested-time.component.html` line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN897C05cmjpdxxwsZH:-NN897C2Edsq63RuKHfU:bht62t8) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.html#L3)):*
> ```HTML
> <div>
>   <table class="table fixed">
>     <col width="300rem" />
> ```

I don't think the col elements are necessary?
___
*[`src/app/proposal/requested-time/requested-time.component.html` line 11 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7WUt18iRd7kH-HQdD:-NN7WUt28TiQTsBxDykz:bf131od) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.html#L11)):*
> ```HTML
>     </thead>
>     <tbody>
>       <ng-container *ngFor="let sm of Object.keys(semesterRequestedTimes)">
> ```

You should sort the semesters.
___
*[`src/app/proposal/requested-time/requested-time.component.html` line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN89Brx5rKQe4Wx27NA:-NN89Brx5rKQe4Wx27NB:b-uipa85) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.html#L13)):*
> ```HTML
>       <ng-container *ngFor="let sm of Object.keys(semesterRequestedTimes)">
>         <tr class="semester-section" (click)="selectSemester(sm)">
>           <th colspan="2" width="600rem">
> ```

The width attribute should be removed.

Instead I would propose a CSS rule:

```

table.table.fixed {
  width: 50%;
}
```
___
*[`src/app/proposal/requested-time/requested-time.component.scss` line 20 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN89PIhCI236an_Nkit:-NN89PIhCI236an_Nkiu:b-7xoj2) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.scss#L20)):*
> ```SCSS
> }
> 
> .comment-text {
> ```

I think this should be removed. (300rem is unrealistically wide anyway, isn't it?)
___
*[`src/app/proposal/requested-time/requested-time.component.ts` line 14 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7ZE_ZDFE4nzNR-7l6:-NN7ZE_ZDFE4nzNR-7l7:b-5b0mdi) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.ts#L14)):*
> ```XML
>   semesterRequestedTimes: { [key: string]: RequestedTime } = {};
>   selectedSemester: string | undefined = undefined;
>   Object = Object;
> ```

Why do you need this line?
___
*[`src/app/proposal/requested-time/requested-time.component.ts` line 19 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7XIrk-1lRDHVzl84i:-NN7XIrk-1lRDHVzl84j:b-b5fw2r) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.ts#L19)):*
> ```XML
>     this.requestedTimes.forEach((r) => {
>       if (this.semesterRequestedTimes.hasOwnProperty(r.semester)) {
>         this.semesterRequestedTimes[r.semester] = r;
> ```

The if and else branch do the same, so something must be amiss here.

Did you mean the following? -

```
this.semesterRequestedTimes = this.requestedTimes.reduce((o, r) => ({ ...o, [r.semester]: r}), {});
```

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/255)* status: all files reviewed (commit messages unreviewed), 11 unresolved discussions (waiting on @hettlage)

___
*[`package.json` line 30 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN8A1yK7t99GemYH-ra:-NNBX5MT60lalOOgvEYc:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/package.json#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be removed, as discussed.
</blockquote></details>

Done.



_Code quote:_
```JSON
bulma-accordion
```
___
*[`src/app/proposal/proposal.component.html` line 25 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7UrIJ-UADDTRQ9yq0:-NNBXKIX7x_wl7zLimCA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/proposal.component.html#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"wm-requested-time" (singular) and "requestedTimes" (plural;) is somewhat inconsistent.
</blockquote></details>

Done.
___
*[`src/app/proposal/proposal.component.html` line 35 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7V0wIEBHk630TwNJV:-NNBXWdEDSe9GscLqnpA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/proposal.component.html#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"time-allocation-table" (singular) and timeAllocations (plural) is somewhat inconsistent.
</blockquote></details>

Done.
___
*[`src/app/proposal/p1-details/p1-details.component.html` line 6 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN8CTItAkRugOi-Iw2p:-NNBhziV1jiIURVtqpwt:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/p1-details/p1-details.component.html#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The requested times table jumps when it is expanded.
</blockquote></details>

Done.
___
*[`src/app/proposal/p1-details/p1-details.component.html` line 12 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7VON76FVznj7Xdzq0:-NNBY8pf3cMD4EYViMfS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/p1-details/p1-details.component.html#L12)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"thesis-students" sounds a bit odd to me, and the "thesis" is more important in the context of the proposal than the specific student. So maybe rather call this element "wm-student-theses"?
</blockquote></details>

Done.
___
*[`src/app/proposal/requested-time/requested-time.component.html` line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN897C05cmjpdxxwsZH:-NNBb1_b4zH7Inh-1z3O:b-hfpv0l) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.html#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the col elements are necessary?
</blockquote></details>

removed
___
*[`src/app/proposal/requested-time/requested-time.component.html` line 11 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7WUt18iRd7kH-HQdD:-NNBYl9L-MXEVwCBtXcr:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.html#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should sort the semesters.
</blockquote></details>

Done.
___
*[`src/app/proposal/requested-time/requested-time.component.html` line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN89Brx5rKQe4Wx27NA:-NNBZZmL8B8CkhTCe2hJ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.html#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The width attribute should be removed.

Instead I would propose a CSS rule:

```

table.table.fixed {
  width: 50%;
}
```
</blockquote></details>

Done.
___
*[`src/app/proposal/requested-time/requested-time.component.scss` line 20 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN89PIhCI236an_Nkit:-NNBZt5u8Ei6kWrEBq3T:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.scss#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think this should be removed. (300rem is unrealistically wide anyway, isn't it?)
</blockquote></details>

Done.
___
*[`src/app/proposal/requested-time/requested-time.component.ts` line 14 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7ZE_ZDFE4nzNR-7l6:-NNBZuwE-oRpCsTg53RA:b-texvbz) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need this line?
</blockquote></details>

to use js Object in the template
___
*[`src/app/proposal/requested-time/requested-time.component.ts` line 19 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7XIrk-1lRDHVzl84i:-NNBb5PzCv0g2B0lHI_x:b-wyn5lz) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.ts#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The if and else branch do the same, so something must be amiss here.

Did you mean the following? -

```
this.semesterRequestedTimes = this.requestedTimes.reduce((o, r) => ({ ...o, [r.semester]: r}), {});
```
</blockquote></details>

Ahh yes I forgot about the Reduce method thank you

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/255)* status: 18 of 28 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`src/app/app.module.ts` line 91 at r3](https://reviewable.io/reviews/saltastroops/web-manager/255#-NNCapeQEWxNOSRxA8ch:-NNCeo3P7slN3tG_ocDj:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/264d93d1e5b5a0ae73c7c68a89b5d202a5e2baed/src/app/app.module.ts#L91)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nitpicking, but shouldn't the name be StudentTheses (i.e.plural)?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/time-allocation-table/time-allocations-table.component.spec.ts` line 5 at r3](https://reviewable.io/reviews/saltastroops/web-manager/255#-NNCb9S69xedm_4GKKv6:-NNCfGIy2tv5qBj5G-Tk:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/264d93d1e5b5a0ae73c7c68a89b5d202a5e2baed/src/app/proposal/general/time-allocation-table/time-allocations-table.component.spec.ts#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

AllocationTableComponent > TimeAllocationsTableComponent
</blockquote></details>

Done.
___
*[`src/app/proposal/requested-time/requested-time.component.scss` line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NNCbxN7Adl2XCRaeqrX:-NNCfMRS9IxpzTCm3065:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.scss#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The files should be called student-theses..., not student-thesis. Also, the parent directory should be renamed.
</blockquote></details>

Done.
___
*[`src/app/proposal/requested-time/requested-time.component.ts` line 14 at r1](https://reviewable.io/reviews/saltastroops/web-manager/255#-NN7ZE_ZDFE4nzNR-7l6:-NNCfsXmBV2uXRdT3cJX:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78724b932ce39dbfa3ec5aa68eaa5e70ec1b848f/src/app/proposal/requested-time/requested-time.component.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add a comment like "Object is used in the template" ?
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
