### PR TITLE
Indicate proposal loading and loading errors

### LINKED ISSUE #158: Show loading indicator while a proposal page is being loaded

### PR DESCRIPTION
**Pull request by hettlage**
Fixes #158.

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/202)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 11 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/202)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @hettlage and @mofokeng-chaka)

___
*[`src/app/app.component.scss` line 34 at r1](https://reviewable.io/reviews/saltastroops/web-manager/202#-NIkq2F_35MQAe3VYoKz:-NIkq2F_35MQAe3VYoL-:b-nhy6a4) ([raw file](https://github.com/saltastroops/web-manager/blob/b291f8fd1b1ac94e03f7a10a9e5eeeceeaf219c3/src/app/app.component.scss#L34)):*
> ```SCSS
>   margin-top: 2rem;
>   margin-left: 2rem;
>   margin-right: 2rem;
> ```

You can use a short hand
`margin: 2rem 2rem 0px  # top left-right bottom`
margin-top have no effect due to padding
`margin: 0rem 2rem `
___
*[`src/app/shared/error-indicator/error-indicator.component.html` line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager/202#-NIl4ixK3O-j_xIGRIC2:-NIl4ixK3O-j_xIGRIC3:b-4q3k1n) ([raw file](https://github.com/saltastroops/web-manager/blob/b291f8fd1b1ac94e03f7a10a9e5eeeceeaf219c3/src/app/shared/error-indicator/error-indicator.component.html#L2)):*
> ```HTML
> <div class="error">
>   <svg
> ```

please acknowledgment to the noun project and since this is static it can be kept on the assets file
___
*[`src/app/shared/loading-indicator/loading-indicator.component.ts` line 9 at r1](https://reviewable.io/reviews/saltastroops/web-manager/202#-NIl5lNr8TGmmlCEJ4j2:-NIl5lNs3_G3mAPBRLyp:bxq5sl5) ([raw file](https://github.com/saltastroops/web-manager/blob/b291f8fd1b1ac94e03f7a10a9e5eeeceeaf219c3/src/app/shared/loading-indicator/loading-indicator.component.ts#L9)):*
> ```XML
> })
> export class LoadingIndicatorComponent {
>   @Input() message = "Loading...";
> ```

it have only one usage message doesn't have to be @input() can be included on the HTML file

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/202)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero, @input, and @mofokeng-chaka)

___
*[`src/app/app.component.scss` line 34 at r1](https://reviewable.io/reviews/saltastroops/web-manager/202#-NIkq2F_35MQAe3VYoKz:-NIlPdLJ5btB_Vi-rIf2:b-mo931x) ([raw file](https://github.com/saltastroops/web-manager/blob/b291f8fd1b1ac94e03f7a10a9e5eeeceeaf219c3/src/app/app.component.scss#L34)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

You can use a short hand
`margin: 2rem 2rem 0px  # top left-right bottom`
margin-top have no effect due to padding
`margin: 0rem 2rem `
</blockquote></details>

I use the shorthand now; but I prefer the one with all four values.

The top margin *does* have an effect, depending on the page content.
___
*[`src/app/shared/error-indicator/error-indicator.component.html` line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager/202#-NIl4ixK3O-j_xIGRIC2:-NIlPxnU6gUs98R48Fza:b-gidh79) ([raw file](https://github.com/saltastroops/web-manager/blob/b291f8fd1b1ac94e03f7a10a9e5eeeceeaf219c3/src/app/shared/error-indicator/error-indicator.component.html#L2)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

please acknowledgment to the noun project and since this is static it can be kept on the assets file
</blockquote></details>

I added the link.

However, I haven't replaced the sag with an img. The reason is that the colour of the icon and the text should be consistent. As changing the text color is not inconceivable (it might be red? a different t grey?), it seems to be better to be able to style the svg content. 
___
*[`src/app/shared/loading-indicator/loading-indicator.component.ts` line 9 at r1](https://reviewable.io/reviews/saltastroops/web-manager/202#-NIl5lNr8TGmmlCEJ4j2:-NIlQlRFEH_4GqwPJDSr:b-rtg8po) ([raw file](https://github.com/saltastroops/web-manager/blob/b291f8fd1b1ac94e03f7a10a9e5eeeceeaf219c3/src/app/shared/loading-indicator/loading-indicator.component.ts#L9)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

it have only one usage message doesn't have to be @input() can be included on the HTML file
</blockquote></details>

I'm not sure I understand what you mean. :-(

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/202)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @input and @mofokeng-chaka)

___
*[`src/app/shared/loading-indicator/loading-indicator.component.ts` line 9 at r1](https://reviewable.io/reviews/saltastroops/web-manager/202#-NIl5lNr8TGmmlCEJ4j2:-NIlY8H21Sc7U1nC0LWc:b-2unrnc) ([raw file](https://github.com/saltastroops/web-manager/blob/b291f8fd1b1ac94e03f7a10a9e5eeeceeaf219c3/src/app/shared/loading-indicator/loading-indicator.component.ts#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not sure I understand what you mean. :-(
</blockquote></details>

I mean there is only one component which is using this.
So the message shouldn't be an input you must add the message on the 
HTML like hard code the message rather than passing it in

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/202)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @hettlage, @input, and @mofokeng-chaka)

___
*[`src/app/app.component.scss` line 32 at r2](https://reviewable.io/reviews/saltastroops/web-manager/202#-NIlf0_37Yd_uehwMhZH:-NIlf0_37Yd_uehwMhZI:b8xc64u) ([raw file](https://github.com/saltastroops/web-manager/blob/fafca8f22d6dae066cb47c3b4bfd671209c0eaff/src/app/app.component.scss#L32)):*
> ```SCSS
> 
> .body {
>   margin: 2rem 2rem 0 2rem;
> ```

`margin: 2rem 2rem 0;` will do the same as well

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/202)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
