### PR TITLE
observation-table-updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Observation section changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/248)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
Do I see correctly that you got rid of the observation component? If so, you might consider removing its code?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/248#-:-NN2vHwcDns3np7kpNb8:b-g8j9dx)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block/block.component.ts` line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager/248#-NN2oofK8SBK20d1L1sR:-NN2oofK8SBK20d1L1sS:bdnkycy) ([raw file](https://github.com/saltastroops/web-manager/blob/dd62732a7542c2f6956893516a00be7663d25bf6/src/app/proposal/blocks/block/block.component.ts#L17)):*
> ```XML
> export class BlockComponent {
>   @Input() block!: Block;
>   firstValidFrom: Date = parseISO("1970-01-01T00:00:00Z");
> ```

This is incorrect. The finder chart validity should be the one supplied by the API.

(Each finder chart may have a different range, which is why there is a "first valid from" and a "last valid until".)
___
*[`src/app/proposal/blocks/block/block.component.ts` line 20 at r1](https://reviewable.io/reviews/saltastroops/web-manager/248#-NN2sjDUEpL1jqtbwW7A:-NN2pvdu2BvA-v-C1iUa:bw7b916) ([raw file](https://github.com/saltastroops/web-manager/blob/dd62732a7542c2f6956893516a00be7663d25bf6/src/app/proposal/blocks/block/block.component.ts#L20)):*
> ```XML
>   lastValidUntil: Date = parseISO("2100-01-01T00:00:00Z");
> 
>   thumbnailFinderChartURL(finderChart: FinderChart): string {
> ```

You are duplicating code here; it might be better to move these functions to the utility file. (or, maybe better, remove all the finder chart stuff from the observation component). But see the general comment above.

**Review by mofokeng-chaka — COMMENTED** [review]
I have removed it now.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/248#-:-NN5HqzT9k8xsfqLjwlw:b-ymbbnz)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/blocks/block/block.component.ts` line 17 at r1](https://reviewable.io/reviews/saltastroops/web-manager/248#-NN2oofK8SBK20d1L1sR:-NN55ETUCTDD5iex_78N:b12m41i) ([raw file](https://github.com/saltastroops/web-manager/blob/dd62732a7542c2f6956893516a00be7663d25bf6/src/app/proposal/blocks/block/block.component.ts#L17)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is incorrect. The finder chart validity should be the one supplied by the API.

(Each finder chart may have a different range, which is why there is a "first valid from" and a "last valid until".)
</blockquote></details>

I see, I just assumed they are fixed because the exact string a being parsed all the time – not using values from the API.
___
*[`src/app/proposal/blocks/block/block.component.ts` line 20 at r1](https://reviewable.io/reviews/saltastroops/web-manager/248#-NN2sjDUEpL1jqtbwW7A:-NN55E4_79OtzOKonzw2:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/dd62732a7542c2f6956893516a00be7663d25bf6/src/app/proposal/blocks/block/block.component.ts#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You are duplicating code here; it might be better to move these functions to the utility file. (or, maybe better, remove all the finder chart stuff from the observation component). But see the general comment above.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
I've implemented the "finder chart validity", so the ball is in your court now.

> Reviewed 5 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/248#-:-NN7MXx8CdfFYpvmZNZX:b-qh5aw8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Review by mofokeng-chaka — COMMENTED** [review]
Thanks, Christian!

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/248#-:-NNAIfwT-DRSVGTV-N5Y:b-ibanp2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
