### PR TITLE
executed-observations-tables-updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Summary of executed observations table updates

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/197)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/197)* status: all files reviewed, 12 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 79 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYAO055eWiWvs_tG1l:-NIYAO055eWiWvs_tG1m:b-7ctt6k) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L79)):*
> ```XML
>   });
> 
>   it("should have the table sorted correctly when clicking on different columns", () => {
> ```

You might test, in an additional test, that that clicking twice (three times) leads to the values being sorted in ascending (descending) order again.
___
*[`cypress/support/components/summary-of-executed-observations.ts` line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIY2bri3trZT9KfoE6h:-NIY2bri3trZT9KfoE6i:bf81n7i) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/cypress/support/components/summary-of-executed-observations.ts#L48)):*
> ```XML
>   ): void {
>     const rowElement = "[data-test=executed-observations-" + column + "]";
>     const columnElement = "[data-testid=executed-observations-" + column + "]";
> ```

I don't think the attribute should be called `data-testid`. Shouldn't it be called `data-test` throughout. Also, IMHO the meaning of "rowElement" and "columnElement" isn't intuitive. Maybe it would be more something like "valueElement" and "headerElement", which might be reflected in the `data-test` value as well.
___
*[`cypress/support/components/summary-of-executed-observations.ts` line 49 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIY3nY744jys4Dsk4ch:-NIY3nY744jys4Dsk4ci:bjbqpj2) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/cypress/support/components/summary-of-executed-observations.ts#L49)):*
> ```XML
>     const rowElement = "[data-test=executed-observations-" + column + "]";
>     const columnElement = "[data-testid=executed-observations-" + column + "]";
>     const sortedBlockIds = [];
> ```

These aren't block ids, but rather column values.

Also, I wouldn't include "sorted", given you are testing whether they are sorted.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 6 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYJAn_Ckm9YqcwYL5O:-NIYJAna3qywDXGMDldU:bop0jxw) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L6)):*
> ```HTML
>   <thead>
>     <tr>
>       <th
> ```

Wouldn't it make sense to make all columns sortable?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss` line 52 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYM8U33CbcmhuFSiVd:-NIYM8U48xX75yTgK10T:b-k8prqc) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss#L52)):*
> ```SCSS
> }
> 
> .pointer.sortable_column:hover {
> ```

These styles are problematic, as they lead to jumps in the column width when you sort a column and then move the cursor.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 23 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYCz6Z3zCcI0f-5RRk:-NIYCz6Z3zCcI0f-5RRl:b-b9k1li) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L23)):*
> ```XML
>   user!: User;
>   showEditBlockButton = false;
>   columnsSortDirections: { [columnName: string]: string | number | null } = {};
> ```

Aren't the only options "ask", "desc" and null?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 23 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYDW2P4eq34KoCttSA:-NIYDW2P4eq34KoCttSB:bvcyt7v) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L23)):*
> ```XML
>   user!: User;
>   showEditBlockButton = false;
>   columnsSortDirections: { [columnName: string]: string | number | null } = {};
> ```

Do you really need this variable? From what I see, you store the sort column and order in other variables anyway?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 24 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYDnG5-4JockAfTlzp:-NIYDnG5-4JockAfTlzq:bfm6hd4) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L24)):*
> ```XML
>   showEditBlockButton = false;
>   columnsSortDirections: { [columnName: string]: string | number | null } = {};
>   isDesc = false;
> ```

Why not `isAsc = true`. Sure, it doesn't matter, but maybe using the default value for the name is slightly more intuitive.

Or, actually, why not use `sortDirection` instead?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 25 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYDI617EeOHm1j0gDe:-NIYDI617EeOHm1j0gDf:b153cr8) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L25)):*
> ```XML
>   columnsSortDirections: { [columnName: string]: string | number | null } = {};
>   isDesc = false;
>   column = "";
> ```

It's not clear what "column" is. Maybe better "sortedColumn"?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 26 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYKF0cC4p1KE2MGKoG:-NIYKF0cC4p1KE2MGKoH:b75az6f) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L26)):*
> ```XML
>   isDesc = false;
>   column = "";
>   filteredBlocks: Observation[] = [];
> ```

Isn't this `sortedObservations` rather than `filteredBlocks`?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 50 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYBo0RE4NhKQ_YPRv7:-NIYBo0RE4NhKQ_YPRv8:bhmq8ql) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L50)):*
> ```XML
>       document.querySelectorAll(".sortable-column");
>     sortableColumnElements.forEach((columnElement) => {
>       const column = columnElement.getAttribute("data-testid");
> ```

"data-testid" (or "data-test") suggest that the attribute is for testing.

So something like `data-observation-property` might be better.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 108 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYCXuc24c_zUs-UIXg:-NIYCXuc24c_zUs-UIXh:b508bvx) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L108)):*
> ```XML
>       asc: !this.isDesc,
>       desc: this.isDesc,
>       sortable_column: true,
> ```

Why not just `sortable`?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/197)* status: 3 of 9 files reviewed, 12 unresolved discussions (waiting on @hettlage)

___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 79 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYAO055eWiWvs_tG1l:-NIaIlnAC3bAteNh1xOJ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L79)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might test, in an additional test, that that clicking twice (three times) leads to the values being sorted in ascending (descending) order again.
</blockquote></details>

Done.
___
*[`cypress/support/components/summary-of-executed-observations.ts` line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIY2bri3trZT9KfoE6h:-NIbvP1c42KA6OkoiF1o:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/cypress/support/components/summary-of-executed-observations.ts#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the attribute should be called `data-testid`. Shouldn't it be called `data-test` throughout. Also, IMHO the meaning of "rowElement" and "columnElement" isn't intuitive. Maybe it would be more something like "valueElement" and "headerElement", which might be reflected in the `data-test` value as well.
</blockquote></details>

Done.
___
*[`cypress/support/components/summary-of-executed-observations.ts` line 49 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIY3nY744jys4Dsk4ch:-NIbw9LTCmtDj5Ct_cRv:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/cypress/support/components/summary-of-executed-observations.ts#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These aren't block ids, but rather column values.

Also, I wouldn't include "sorted", given you are testing whether they are sorted.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 6 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYJAn_Ckm9YqcwYL5O:-NIfHM6o7znynatSSxwN:bjp5tt) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't it make sense to make all columns sortable?
</blockquote></details>

I have made most of them sortable, some we cannot sort by, e.g rejection reason, edit and data.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss` line 52 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYM8U33CbcmhuFSiVd:-NIfW6TwBGXnFoM--ITe:bvsj6cf) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

These styles are problematic, as they lead to jumps in the column width when you sort a column and then move the cursor.
</blockquote></details>

I have changed them accordingly and the element no longer jump.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 23 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYCz6Z3zCcI0f-5RRk:-NIfRwfI6rgq_tx11y1y:b-f1i376) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Aren't the only options "ask", "desc" and null?
</blockquote></details>

The options are actually "asc", "dec" and an empty string, and null is not part of the options.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 23 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYDW2P4eq34KoCttSA:-NIfTd4LDnC1GZf6Ovef:b-f7ecyf) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Do you really need this variable? From what I see, you store the sort column and order in other variables anyway?
</blockquote></details>

You're right, it is not needed, I have removed it.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 24 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYDnG5-4JockAfTlzp:-NIfTwM49Z5QIR29tTW8:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why not `isAsc = true`. Sure, it doesn't matter, but maybe using the default value for the name is slightly more intuitive.

Or, actually, why not use `sortDirection` instead?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 25 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYDI617EeOHm1j0gDe:-NIfU7rD98MsesDL24Qz:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It's not clear what "column" is. Maybe better "sortedColumn"?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 26 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYKF0cC4p1KE2MGKoG:-NIfUInj5l0dsS3WxjnJ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this `sortedObservations` rather than `filteredBlocks`?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 50 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYBo0RE4NhKQ_YPRv7:-NIfVgE_5HLt85NO0PBY:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"data-testid" (or "data-test") suggest that the attribute is for testing.

So something like `data-observation-property` might be better.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 108 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYCXuc24c_zUs-UIXg:-NIfW4Zw9anMNsPZOfaS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L108)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why not just `sortable`?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/197)* status: all files reviewed, 5 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.scss` line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIgY4Pe6N0dIaYW_Lgu:-NIgY4Pe6N0dIaYW_Lgv:b4owawb) ([raw file](https://github.com/saltastroops/web-manager/blob/f7d49386c3023ee6fc7da289b0fd83e1890d59dd/src/app/proposal/blocks/block-summaries/block-summaries.component.scss#L73)):*
> ```SCSS
> .pointer.sortable_column:hover {
>   background: $primary-header;
>   -webkit-backface-visibility: hidden;
> ```

Looking at the documentation, I don;'t see why yiu would need the -webkit prefix and why the style would have any effect?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 23 at r1](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIYCz6Z3zCcI0f-5RRk:-NIhVLt5EIqOORxcbAyv:b-b11d47) ([raw file](https://github.com/saltastroops/web-manager/blob/0de77dd28f69705e006fe1cdfc0a4ff71d5d616c/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L23)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

The options are actually "asc", "dec" and an empty string, and null is not part of the options.
</blockquote></details>

Then you could still use "asc" | "desc" | "".
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 23 at r2](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIhUn6_4W91xiaazGbb:-NIhUn6_4W91xiaazGbc:bjel040) ([raw file](https://github.com/saltastroops/web-manager/blob/f7d49386c3023ee6fc7da289b0fd83e1890d59dd/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L23)):*
> ```XML
>   user!: User;
>   showEditBlockButton = false;
>   columnsSortDirections: { [columnName: string]: string } = {};
> ```

I'm still not convinced you need this array. Also, there is a subtle bug. (Click on column A, then on column B, and then on column A again Yiu would expect column A is sorted in ascending order now, but it is actually sorted in descending order.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 47 at r2](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIgeyMuEG8jxe6AuNe8:-NIgeyMuEG8jxe6AuNe9:b7h5t00) ([raw file](https://github.com/saltastroops/web-manager/blob/f7d49386c3023ee6fc7da289b0fd83e1890d59dd/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L47)):*
> ```XML
>     this.sortedObservations = this.observations;
>     const sortableColumnElements =
>       document.querySelectorAll(".sortable-column");
> ```

Isn't using `querySelectorAll` in Angular considered bad practice?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 49 at r2](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIgfAIf79A-1v1VP8T4:-NIgfAIf79A-1v1VP8T5:b-23di67) ([raw file](https://github.com/saltastroops/web-manager/blob/f7d49386c3023ee6fc7da289b0fd83e1890d59dd/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L49)):*
> ```XML
>       document.querySelectorAll(".sortable-column");
>     sortableColumnElements.forEach((columnElement) => {
>       const column = columnElement.getAttribute("data-observation-property");
> ```

Are you sure you need this? (And if you'd, shouldn't it be a class attribute value?)

**Review by hettlage — COMMENTED** [review]
Here is a really general comment... Wouldn't it make sense to rather solve the sorting problem in general? After all, there are other tables to sort.

https://sankhadip.medium.com/how-to-sort-table-rows-according-column-in-angular-9-b04fdafb4140 seems to explain how to add sorting to tables in general by means of a directive.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/197#-:-NIiSVXADj3rhJyJe-0m:bo47h4l)* status: all files reviewed, 5 unresolved discussions (waiting on @mofokeng-chaka)

**Review by hettlage — CHANGES_REQUESTED** [review]
Well, it gets the sort order wrong now. It sorts in descending order when it shows ascending in the header, and vice versa.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/197#-:-NIqVeQmCBcuFaVMLeq1:bre1b9r)* status: all files reviewed, 6 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/sort.directive.ts` line 14 at r3](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIqUI4H45TaDQS5HXXb:-NIqUI4H45TaDQS5HXXc:b-pqq2s8) ([raw file](https://github.com/saltastroops/web-manager/blob/a50fa7c53a4e94dd8a6a2fa51692c87d14dc4bdf/src/app/sort.directive.ts#L14)):*
> ```XML
> @Directive({
>   // eslint-disable-next-line @angular-eslint/directive-selector
>   selector: "[appSort]",
> ```

The name of the directive should be "wmSort" -- and then you don't have to disable ESLint... ;-)
___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.scss` line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIgY4Pe6N0dIaYW_Lgu:-NIqW-ISB0joNX--JbA9:b-1ezybx) ([raw file](https://github.com/saltastroops/web-manager/blob/f7d49386c3023ee6fc7da289b0fd83e1890d59dd/src/app/proposal/blocks/block-summaries/block-summaries.component.scss#L73)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have removed it now.
</blockquote></details>

I still see it?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 10 at r3](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIqWIEzAA5xjULtYRHr:-NIqWIEzAA5xjULtYRHs:bbem3jn) ([raw file](https://github.com/saltastroops/web-manager/blob/a50fa7c53a4e94dd8a6a2fa51692c87d14dc4bdf/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L10)):*
> ```HTML
>         (click)="onColumnClick($event, 'blockName')"
>         [appSort]="observations"
>         data-order="desc"
> ```

You shouldn't have to include the data-order attribute,
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss` line 59 at r3](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIqWc-12UzjCEtU8BiC:-NIqWc-12UzjCEtU8BiD:b-7iv9cs) ([raw file](https://github.com/saltastroops/web-manager/blob/a50fa7c53a4e94dd8a6a2fa51692c87d14dc4bdf/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss#L59)):*
> ```SCSS
> td {
>   width: 215px;
>   overflow: hidden;
> ```

Isn't this potentially hiding content?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 23 at r2](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIhUn6_4W91xiaazGbb:-NIqWkXg4AjSAZEcnxXN:b-tv3vu9) ([raw file](https://github.com/saltastroops/web-manager/blob/f7d49386c3023ee6fc7da289b0fd83e1890d59dd/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L23)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I am not sure which array you are referring to, if you mean the object, I need it to keep track sort order of the columns. In principle, the object is used to solve the bug you are talking about.
</blockquote></details>

I meant the object. Technically, you wouldn't need the object though, as you are only interested in the previous and current value.

But I think there should be no sorting logic implementation whatsoever in this component. Can we have a chat about this, please?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/197)* status: 9 of 14 files reviewed, 6 unresolved discussions (waiting on @hettlage)

___
*[`src/app/sort.directive.ts` line 14 at r3](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIqUI4H45TaDQS5HXXb:-NJ5X1D2ARVajYV9R-yA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/a50fa7c53a4e94dd8a6a2fa51692c87d14dc4bdf/src/app/sort.directive.ts#L14)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name of the directive should be "wmSort" -- and then you don't have to disable ESLint... ;-)
</blockquote></details>

Done.
___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.scss` line 73 at r2](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIgY4Pe6N0dIaYW_Lgu:-NJ3tl9dDNRjz7xw73ac:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f7d49386c3023ee6fc7da289b0fd83e1890d59dd/src/app/proposal/blocks/block-summaries/block-summaries.component.scss#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I still see it?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 10 at r3](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIqWIEzAA5xjULtYRHr:-NJ5TcudESz5yQhnuT3j:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/a50fa7c53a4e94dd8a6a2fa51692c87d14dc4bdf/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You shouldn't have to include the data-order attribute,
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss` line 59 at r3](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIqWc-12UzjCEtU8BiC:-NJ5Twfm4Na6PqL6BM2x:b-rrjqog) ([raw file](https://github.com/saltastroops/web-manager/blob/a50fa7c53a4e94dd8a6a2fa51692c87d14dc4bdf/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.scss#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this potentially hiding content?
</blockquote></details>

Not sure, I no longer see its effects and so I have removed it.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 23 at r2](https://reviewable.io/reviews/saltastroops/web-manager/197#-NIhUn6_4W91xiaazGbb:-NJ5U5H88IMtF5z8D6m1:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/f7d49386c3023ee6fc7da289b0fd83e1890d59dd/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I meant the object. Technically, you wouldn't need the object though, as you are only interested in the previous and current value.

But I think there should be no sorting logic implementation whatsoever in this component. Can we have a chat about this, please?
</blockquote></details>

Done.

**Review by mofokeng-chaka — COMMENTED** [review]
I am aware there are still some problems with the header direction. That is what I am currently battling with—trying to correctly show the sort direction for the clicked column and then hide the sort direction for the rest of the columns.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/197#-:-NJ5X6gE91Hl_vvRofNS:b99u8nq)* status: 9 of 14 files reviewed, 6 unresolved discussions (waiting on @hettlage)

**Pull request merged**
