### PR TITLE
show-investigator-institution

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Show correct institution value on investigator table

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/251)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/251)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/investigators/investigators.component.html` line 47 at r1](https://reviewable.io/reviews/saltastroops/web-manager/251#-NN6xiht3_DEUycMIxAx:-NN6xihu6DB7jtOwM-yI:blh1c6u) ([raw file](https://github.com/saltastroops/web-manager/blob/48e860eedd8468b3aebfee41b11f26bd49ecd868/src/app/proposal/investigators/investigators.component.html#L47)):*
> ```HTML
>       <td>{{ i.affiliation.name }}</td>
>       <td>{{ i.affiliation.department }}</td>
>       
> ```


Do we still need this TODO this should be correct now

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/251)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/251)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @hettlage)

___
*[`src/app/proposal/investigators/investigators.component.html` line 47 at r1](https://reviewable.io/reviews/saltastroops/web-manager/251#-NN6xiht3_DEUycMIxAx:-NNAKhlp-UxW4UWoXrj2:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/48e860eedd8468b3aebfee41b11f26bd49ecd868/src/app/proposal/investigators/investigators.component.html#L47)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Then you should remove it... :-)
</blockquote></details>

Done.

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/251)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Pull request merged**
