### PR TITLE
proper-values-units

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Adding values units

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/200)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/200)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block/observing-conditions/observing-conditions.component.html` line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager/200#-NIY-MR1CnNWqwSSHMEa:-NIY48lJ5wI8u98mp0fi:b-njne2j) ([raw file](https://github.com/saltastroops/web-manager/blob/0771e7899a6b795815b510a27583c2b063bcd083/src/app/proposal/blocks/block/observing-conditions/observing-conditions.component.html#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency reasons, it might be better to add "sec" to the values instead (as you did for the iterations table).
</blockquote></details>

Having said that, this makes sorting harder, of course, because then you have strings instead of numbers.

So maybe rather keep the seconds in the header but change the iterations table instead?
___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.html` line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager/200#-NIY-dAjC-GcZjsS-sPQ:-NIY4XIb-KblsDc3mpwL:bfa2het) ([raw file](https://github.com/saltastroops/web-manager/blob/0771e7899a6b795815b510a27583c2b063bcd083/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

For consistency reasons, it might be better to add "sec" to the values instead (as you did for the iterations table).
</blockquote></details>

Having said that, this makes sorting harder, of course, because then you have strings instead of numbers.

So maybe rather keep the seconds in the header but change the iterations table instead?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/200)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/blocks/block/observing-conditions/observing-conditions.component.html` line 13 at r1](https://reviewable.io/reviews/saltastroops/web-manager/200#-NIY-MR1CnNWqwSSHMEa:-NIa315Y2Jz6WmYVvlr7:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0771e7899a6b795815b510a27583c2b063bcd083/src/app/proposal/blocks/block/observing-conditions/observing-conditions.component.html#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Having said that, this makes sorting harder, of course, because then you have strings instead of numbers.

So maybe rather keep the seconds in the header but change the iterations table instead?

</blockquote></details>

Done.
___
*[`src/app/proposal/blocks/block-summaries/block-summaries.component.html` line 48 at r1](https://reviewable.io/reviews/saltastroops/web-manager/200#-NIY-dAjC-GcZjsS-sPQ:-NIa32ta2PLNyyxw3JuO:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0771e7899a6b795815b510a27583c2b063bcd083/src/app/proposal/blocks/block-summaries/block-summaries.component.html#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Having said that, this makes sorting harder, of course, because then you have strings instead of numbers.

So maybe rather keep the seconds in the header but change the iterations table instead?
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Review by hettlage — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
