### PR TITLE
proposal-status-bg-colour

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Display correct background colour for a given proposal status

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/211)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/211)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/styles.scss` line 213 at r1](https://reviewable.io/reviews/saltastroops/web-manager/211#-NMEMPqO3IL-3aDV3-gR:-NMEMPqO3IL-3aDV3-gS:bb7s1z4) ([raw file](https://github.com/saltastroops/web-manager/blob/a0678e2dfc7b5817f18af3b29595e7b992740436/src/styles.scss#L213)):*
> ```SCSS
> }
> 
> .is-red-background {
> ```

Shouldn't the class names be more semantic, such as is-pending, is-ok, its-danger?

Also it seems that the same styles are used in different components, and you should consider using a CSS variable for the color in this case or defining the CSS styles globally.

There might also be suitable Bulma styles already?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/211)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/styles.scss` line 213 at r1](https://reviewable.io/reviews/saltastroops/web-manager/211#-NMEMPqO3IL-3aDV3-gR:-NMEQUDnEUmSdijd1Kcl:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/a0678e2dfc7b5817f18af3b29595e7b992740436/src/styles.scss#L213)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't the class names be more semantic, such as is-pending, is-ok, its-danger?

Also it seems that the same styles are used in different components, and you should consider using a CSS variable for the color in this case or defining the CSS styles globally.

There might also be suitable Bulma styles already?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/211)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/styles.scss` line 213 at r1](https://reviewable.io/reviews/saltastroops/web-manager/211#-NMEMPqO3IL-3aDV3-gR:-NMZ55TY7fMkB0R6_S8F:brja5ln) ([raw file](https://github.com/saltastroops/web-manager/blob/a0678e2dfc7b5817f18af3b29595e7b992740436/src/styles.scss#L213)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You might consider removing the styles not needed any longer...

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/211)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/styles.scss` line 213 at r1](https://reviewable.io/reviews/saltastroops/web-manager/211#-NMEMPqO3IL-3aDV3-gR:-NMZ9YUE8qAxJVu3qAPB:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/a0678e2dfc7b5817f18af3b29595e7b992740436/src/styles.scss#L213)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might consider removing the styles not needed any longer...
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/211)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
