### PR TITLE
github-actions-status

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Display GitHub Actions workflow status on the README file

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/198)

### CODE REVIEW

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/198)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`README.md` line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager/198#-NIY0Hbo1YqNVD6EHPEa:-NIa44deCdNEUsE9KJQo:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/072f22b8c70847ec883a2f7b75e24d1bc02650d4/README.md#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Nitpicking, but this is a Test Status rather than Build Status...

Maybe just say "Tests"?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/198)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`README.md` line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager/198#-NIY0Hbo1YqNVD6EHPEa:-NIb2keEAh3WgM1moQ6G:b-fk5ltp) ([raw file](https://github.com/saltastroops/web-manager/blob/072f22b8c70847ec883a2f7b75e24d1bc02650d4/README.md#L3)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually I meant "Tests", not "Tests Status".

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/198)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`README.md` line 3 at r1](https://reviewable.io/reviews/saltastroops/web-manager/198#-NIY0Hbo1YqNVD6EHPEa:-NIfpvMMCOuda0_TXRLD:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/072f22b8c70847ec883a2f7b75e24d1bc02650d4/README.md#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Actually I meant "Tests", not "Tests Status".
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/198)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
