### PR TITLE
Login after server error

### LINKED ISSUE #254: Login issue
If you

1. Log in
2 Stop the backend server
3. Reload the Web Manager
4. Try to log in
5. Restart the backend server
6. Try to log in again

Then you are not redirected even though the API login request succeeds.

### PR DESCRIPTION
**Pull request by hettlage**
Fixes #254

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/311)

### CODE REVIEW

**Review by mofokeng-chaka — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/311)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`cypress/e2e/login/login.cy.ts` line 95 at r1](https://reviewable.io/reviews/saltastroops/web-manager/311#-NQ9OYiK-QNqmtkIjk-z:-NQ9OYiL2iUTI0BMc_C1:beuiu7i) ([raw file](https://github.com/saltastroops/web-manager/blob/637597149365bf1fd985001b4232651108f6214b/cypress/e2e/login/login.cy.ts#L95)):*
> ```XML
>   });
> 
>   it.only("should handle logging in again after an error", () => {
> ```

Might have forgot to remove ".only".

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/311)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

**Review by hettlage — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/311)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero and @mofokeng-chaka)

___
*[`cypress/e2e/login/login.cy.ts` line 95 at r1](https://reviewable.io/reviews/saltastroops/web-manager/311#-NQ9OYiK-QNqmtkIjk-z:-NQAxpYiBCoMChpaR5KF:boh5qfw) ([raw file](https://github.com/saltastroops/web-manager/blob/637597149365bf1fd985001b4232651108f6214b/cypress/e2e/login/login.cy.ts#L95)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Might have forgot to remove ".only".
</blockquote></details>

Indeed... Thanks for catching this!

**Review by mofokeng-chaka — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/311)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hettlage)

**Pull request merged**
