### PR TITLE
Propriotory period

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/256)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/256)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager/256#-NNBppfV5sJxxeIiBIZN:-NNBppfV5sJxxeIiBIZO:b-35bvag) ([raw file](https://github.com/saltastroops/web-manager/blob/d4a4a4f87e5001b29c62f591bc8c26ed86e35996/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L15)):*
> ```XML
>   releaseDate!: Date;
>   ngOnInit(): void {
>     const tmpDate = new Date(
> ```

Shouldn't this done with darts-fns's `parseISO` function?
___
*[`src/app/proposal/general/proposal-details/edit-proprietary-period-modal/edit-proprietary-period-modal.component.html` line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager/256#-NNBqdlG2JzIed-r4hBs:-NNBqdlH2C-3DgRmM2O4:b7zho7i) ([raw file](https://github.com/saltastroops/web-manager/blob/d4a4a4f87e5001b29c62f591bc8c26ed86e35996/src/app/proposal/general/proposal-details/edit-proprietary-period-modal/edit-proprietary-period-modal.component.html#L27)):*
> ```HTML
>             <ng-container>
>               <p class="info-text has-text-info-dark is-small">
>                 The motivation is only required when proprietary period is
> ```

when proprietary > when the proprietary
___
*[`src/app/proposal/general/proposal-details/edit-proprietary-period-modal/edit-proprietary-period-modal.component.ts` line 42 at r1](https://reviewable.io/reviews/saltastroops/web-manager/256#-NNBr2ux4dn6CeAuLkZw:-NNBr2ux4dn6CeAuLkZx:bfnvsfo) ([raw file](https://github.com/saltastroops/web-manager/blob/d4a4a4f87e5001b29c62f591bc8c26ed86e35996/src/app/proposal/general/proposal-details/edit-proprietary-period-modal/edit-proprietary-period-modal.component.ts#L42)):*
> ```XML
>       this.error = undefined;
>     } else {
>       this.error = "The proprietary period should be a number of month.";
> ```

should be > must be

of month > of months
___
*[`src/app/types/proposal.ts` line 189 at r1](https://reviewable.io/reviews/saltastroops/web-manager/256#-NNCa1q95WKZIxriu8h7:-NNCa1q95WKZIxriu8h8:b-9cl1av) ([raw file](https://github.com/saltastroops/web-manager/blob/d4a4a4f87e5001b29c62f591bc8c26ed86e35996/src/app/types/proposal.ts#L189)):*
> ```XML
> export type ProgressReportsUrls = { [key: string]: { [key: string]: string } };
> 
> export interface NewProprietaryPeriod {
> ```

Shouldn't this type inherit from ProprietaryPeriod? And why is the motivation required?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/256)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.ts` line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager/256#-NNBppfV5sJxxeIiBIZN:-NNCiEH1CH2qkRh8WAdZ:b-4ptzlp) ([raw file](https://github.com/saltastroops/web-manager/blob/d4a4a4f87e5001b29c62f591bc8c26ed86e35996/src/app/proposal/general/proposal-details/details-table/details-table.component.ts#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this done with darts-fns's `parseISO` function?
</blockquote></details>

there Exists this Error: (intermediate value).parseISO is not a function.

and we are safe in our case since we are only parsing a string with just a date and no time
so `parseISO` will have no effect
___
*[`src/app/proposal/general/proposal-details/edit-proprietary-period-modal/edit-proprietary-period-modal.component.html` line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager/256#-NNBqdlG2JzIed-r4hBs:-NNCjB2y7rEvJPM4LbAq:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/d4a4a4f87e5001b29c62f591bc8c26ed86e35996/src/app/proposal/general/proposal-details/edit-proprietary-period-modal/edit-proprietary-period-modal.component.html#L27)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

when proprietary > when the proprietary
</blockquote></details>

Done.
___
*[`src/app/proposal/general/proposal-details/edit-proprietary-period-modal/edit-proprietary-period-modal.component.ts` line 42 at r1](https://reviewable.io/reviews/saltastroops/web-manager/256#-NNBr2ux4dn6CeAuLkZw:-NNCjOIY5eGGdmhDKczN:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/d4a4a4f87e5001b29c62f591bc8c26ed86e35996/src/app/proposal/general/proposal-details/edit-proprietary-period-modal/edit-proprietary-period-modal.component.ts#L42)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

should be > must be

of month > of months
</blockquote></details>

Done.
___
*[`src/app/types/proposal.ts` line 189 at r1](https://reviewable.io/reviews/saltastroops/web-manager/256#-NNCa1q95WKZIxriu8h7:-NNCkAJF2ssRzKY3MqvD:b-fg36jp) ([raw file](https://github.com/saltastroops/web-manager/blob/d4a4a4f87e5001b29c62f591bc8c26ed86e35996/src/app/types/proposal.ts#L189)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this type inherit from ProprietaryPeriod? And why is the motivation required?
</blockquote></details>

Ahhh yes correct nice catch

**Review by hettlage — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/256)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Review by hettlage — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
