### PR TITLE
Fix Dockerfile.

### PR DESCRIPTION
**Pull request by Eb-Zeero**
* environments variables

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/131)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/131)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`Dockerfile` line 11 at r1](https://reviewable.io/reviews/saltastroops/web-manager/131#-N96oq1-CYzoy18YZUOw:-N96oq102SSXBUQoWIOL:biebs2) ([raw file](https://github.com/saltastroops/web-manager/blob/ec8e4d1f8ca029a70ee17b4325e062305cb63072/Dockerfile#L11)):*
> ```Dockerfile
> COPY --from=builder /web-manager/dist/web-manager/ /usr/share/nginx/html
> COPY nginx.conf /etc/nginx/conf.d/default.conf
> RUN sed -i --debug "s|API_SERVER_URL|$API_SERVER_URL|g" /etc/nginx/conf.d/default.conf
> ```

I don't think you need the `--debug` flag?
___
*[`docker-compose.yml` line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager/131#-N96pIyU4MH3pSiozS39:-N96pIyU4MH3pSiozS3A:b-hh9p6t) ([raw file](https://github.com/saltastroops/web-manager/blob/ec8e4d1f8ca029a70ee17b4325e062305cb63072/docker-compose.yml#L8)):*
> ```YAML
>       context: . # Location of our Dockerfile
>       args:
>         - API_SERVER_URL=${API_SERVER_URL}
> ```

Why do you need to pass API_SERVER_URL as an ARG if you already pass it as an environment variable?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/131)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`Dockerfile` line 11 at r1](https://reviewable.io/reviews/saltastroops/web-manager/131#-N96oq1-CYzoy18YZUOw:-N9AwDn5CjIu068Y8KSo:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/ec8e4d1f8ca029a70ee17b4325e062305cb63072/Dockerfile#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you need the `--debug` flag?
</blockquote></details>

Done.
___
*[`docker-compose.yml` line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager/131#-N96pIyU4MH3pSiozS39:-N9AwFAb2vDbwlOrmHrb:b-eqy2la) ([raw file](https://github.com/saltastroops/web-manager/blob/ec8e4d1f8ca029a70ee17b4325e062305cb63072/docker-compose.yml#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you need to pass API_SERVER_URL as an ARG if you already pass it as an environment variable?
</blockquote></details>

I am passing this argument to use on the Docker file

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/131)* status: all files reviewed, 2 unresolved discussions (waiting on @Eb-Zeero)

___
*[`Dockerfile` line 11 at r1](https://reviewable.io/reviews/saltastroops/web-manager/131#-N96oq1-CYzoy18YZUOw:-N9B4NJyAiaJRvjEq_tZ:b-7xfqh5) ([raw file](https://github.com/saltastroops/web-manager/blob/ec8e4d1f8ca029a70ee17b4325e062305cb63072/Dockerfile#L11)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still there?
___
*[`docker-compose.yml` line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager/131#-N96pIyU4MH3pSiozS39:-N9B4PPY9s8J8FK9CN1f:b-t15qa8) ([raw file](https://github.com/saltastroops/web-manager/blob/ec8e4d1f8ca029a70ee17b4325e062305cb63072/docker-compose.yml#L8)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I am passing this argument to use on the Docker file
</blockquote></details>

Ah, it seems you indeed need both. Sorry.

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/131)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`Dockerfile` line 11 at r1](https://reviewable.io/reviews/saltastroops/web-manager/131#-N96oq1-CYzoy18YZUOw:-N9BUxQ6Ax6w--zWDZ8M:b-8oqlyu) ([raw file](https://github.com/saltastroops/web-manager/blob/ec8e4d1f8ca029a70ee17b4325e062305cb63072/Dockerfile#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It's still there?
</blockquote></details>

sorry forgot to push
___
*[`docker-compose.yml` line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager/131#-N96pIyU4MH3pSiozS39:-N9BUwJF01U7dREsAiSB:b-k73z76) ([raw file](https://github.com/saltastroops/web-manager/blob/ec8e4d1f8ca029a70ee17b4325e062305cb63072/docker-compose.yml#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, it seems you indeed need both. Sorry.
</blockquote></details>

thanks

**Pull request merged**
