### PR TITLE
investigators-table-legend

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Investigators table legend

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/212)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/212)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/investigators/investigators.component.html` line 20 at r1](https://reviewable.io/reviews/saltastroops/web-manager/212#-NMEJtZT0t3smStDbqs1:-NMEJtZUCKajJSrSra4s:b-592vja) ([raw file](https://github.com/saltastroops/web-manager/blob/78bb35ac5354c9c6591e6913f780ec105dc3bc70/src/app/proposal/investigators/investigators.component.html#L20)):*
> ```HTML
>       *ngFor="let i of investigators"
>       [class.is-green-background]="i.hasApprovedProposal === true"
>       [class.is-red-background]="i.hasApprovedProposal === false"
> ```

Shouldn't `undefined` be impossible?
___
*[`src/app/proposal/investigators/investigators.component.html` line 88 at r1](https://reviewable.io/reviews/saltastroops/web-manager/212#-NMEKUmi9FjF-aJtGuec:-NMEKUmi9FjF-aJtGued:b-9x3rkk) ([raw file](https://github.com/saltastroops/web-manager/blob/78bb35ac5354c9c6591e6913f780ec105dc3bc70/src/app/proposal/investigators/investigators.component.html#L88)):*
> ```HTML
>       <td colspan="5">
>         <span
>           >Investigator still has to approve/refuse submission of the the
> ```

submission > the submission

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/212)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/investigators/investigators.component.html` line 20 at r1](https://reviewable.io/reviews/saltastroops/web-manager/212#-NMEJtZT0t3smStDbqs1:-NMELgEiBNCQbY266k0I:bk8ql4d) ([raw file](https://github.com/saltastroops/web-manager/blob/78bb35ac5354c9c6591e6913f780ec105dc3bc70/src/app/proposal/investigators/investigators.component.html#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't `undefined` be impossible?
</blockquote></details>

That's true, i have fixed this.
___
*[`src/app/proposal/investigators/investigators.component.html` line 88 at r1](https://reviewable.io/reviews/saltastroops/web-manager/212#-NMEKUmi9FjF-aJtGuec:-NMELllo4Y2oz-cnf3L5:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78bb35ac5354c9c6591e6913f780ec105dc3bc70/src/app/proposal/investigators/investigators.component.html#L88)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

submission > the submission
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/212)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/investigators/investigators.component.html` line 73 at r1](https://reviewable.io/reviews/saltastroops/web-manager/212#-NMELD062PR_tQEWaU2O:-NMELD062PR_tQEWaU2P:bitc3j2) ([raw file](https://github.com/saltastroops/web-manager/blob/78bb35ac5354c9c6591e6913f780ec105dc3bc70/src/app/proposal/investigators/investigators.component.html#L73)):*
> ```HTML
>   <tbody>
>     <tr>
>       <td colspan="2" class="is-red-background"></td>
> ```

Shouldn't the class names be more semantic, such as is-pending, is-ok, its-danger?

Also it seems that the same styles are used in different components, and you should consider using a CSS variable for the color in this case or defining the CSS styles globally.
___
*[`src/app/proposal/investigators/investigators.component.html` line 88 at r1](https://reviewable.io/reviews/saltastroops/web-manager/212#-NMEKUmi9FjF-aJtGuec:-NMEM3Tg73J_ToqrpgpF:b-egd2ii) ([raw file](https://github.com/saltastroops/web-manager/blob/78bb35ac5354c9c6591e6913f780ec105dc3bc70/src/app/proposal/investigators/investigators.component.html#L88)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now ir=t reads "the the proposal". Definitely one "the" too many... ;-)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/212)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/investigators/investigators.component.html` line 73 at r1](https://reviewable.io/reviews/saltastroops/web-manager/212#-NMELD062PR_tQEWaU2O:-NMEOEgN15yjH5Obm8Cr:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/78bb35ac5354c9c6591e6913f780ec105dc3bc70/src/app/proposal/investigators/investigators.component.html#L73)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't the class names be more semantic, such as is-pending, is-ok, its-danger?

Also it seems that the same styles are used in different components, and you should consider using a CSS variable for the color in this case or defining the CSS styles globally.
</blockquote></details>

Done.
___
*[`src/app/proposal/investigators/investigators.component.html` line 88 at r1](https://reviewable.io/reviews/saltastroops/web-manager/212#-NMEKUmi9FjF-aJtGuec:-NMEONLR2rV5Uv_H0wKT:b8nl1em) ([raw file](https://github.com/saltastroops/web-manager/blob/78bb35ac5354c9c6591e6913f780ec105dc3bc70/src/app/proposal/investigators/investigators.component.html#L88)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Now ir=t reads "the the proposal". Definitely one "the" too many... ;-)
</blockquote></details>

It should be fine now.

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/212)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
