### PR TITLE
nir-instrument

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
NIR instrument table(s)

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/143)

### CODE REVIEW

**Review by Eb-Zeero — CHANGES_REQUESTED** [review]
I need to see this in action...
but I have no NIR proposal

> Reviewed 10 of 25 files at r1, 11 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/143#-:-NEkjGPs0iQikz7Fgv2o:b-nb81mh)* status: 21 of 30 files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block/payload-configuration/payload-configuration.component.ts` line 37 at r2](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEke7W25fJN0ZH-q1iA:-NEke7W25fJN0ZH-q1iB:bctzv95) ([raw file](https://github.com/saltastroops/web-manager/blob/58a9462bffb73c640fd95bcbf5666a092fef881b/src/app/proposal/blocks/block/payload-configuration/payload-configuration.component.ts#L37)):*
> ```XML
>     } else if (instruments.bvit) {
>       this.instrument = "BVIT";
>     } else {
> ```

you are missing if here in case the instrument is something else
___
*[`src/app/proposal/instruments/nir/nir.component.scss` line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEkeZKo-DRLfObpEZ8-:-NEkeZKo-DRLfObpEZ80:b-v0lp0c) ([raw file](https://github.com/saltastroops/web-manager/blob/58a9462bffb73c640fd95bcbf5666a092fef881b/src/app/proposal/instruments/nir/nir.component.scss#L1)):*
> ```SCSS
> @import "../../../../styles";
> ```

I do not see why you need this import.
you can use `@import "src/styles";`
___
*[`src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEkgj6q-sCfeYWKfSqo:-NEkgj6q-sCfeYWKfSqp:bota5gx) ([raw file](https://github.com/saltastroops/web-manager/blob/58a9462bffb73c640fd95bcbf5666a092fef881b/src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html#L14)):*
> ```HTML
>         <th>Groups</th>
>         <th>Ramps</th>
>         <th>Reads per sample</th>
> ```

As per Daniel's comment, we need to start each word with a capital letter. 
all that don't follow this need to be updated.
___
*[`src/app/proposal/instruments/nir/nir-general-info/nir-general-info.component.ts` line 3 at r2](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEki1GdDDsml1zhTDlg:-NEki1GdDDsml1zhTDlh:b88u9my) ([raw file](https://github.com/saltastroops/web-manager/blob/58a9462bffb73c640fd95bcbf5666a092fef881b/src/app/proposal/instruments/nir/nir-general-info/nir-general-info.component.ts#L3)):*
> ```XML
> import { Component, Input } from "@angular/core";
> 
> import { Nir, NirProcedure } from "../../../../types/nir";
> ```

unused import

**Review by mofokeng-chaka — COMMENTED** [review]
That is weird. I think it must be the database you're connected to. You must use either sdb_daily or sdb_daily_test to see the NIR_Test block.

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/143#-:-NEo9nx_5jvil0-XgVD2:b-oe7ptc)* status: 21 of 30 files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/blocks/block/payload-configuration/payload-configuration.component.ts` line 37 at r2](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEke7W25fJN0ZH-q1iA:-NEoC4De-FTILBZ2OH9F:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/58a9462bffb73c640fd95bcbf5666a092fef881b/src/app/proposal/blocks/block/payload-configuration/payload-configuration.component.ts#L37)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

you are missing if here in case the instrument is something else
</blockquote></details>

Done.
___
*[`src/app/proposal/instruments/nir/nir.component.scss` line 1 at r2](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEkeZKo-DRLfObpEZ8-:-NEoCDVjERsmPdiLy_eZ:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/58a9462bffb73c640fd95bcbf5666a092fef881b/src/app/proposal/instruments/nir/nir.component.scss#L1)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I do not see why you need this import.
you can use `@import "src/styles";`
</blockquote></details>

Done.
___
*[`src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html` line 14 at r2](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEkgj6q-sCfeYWKfSqo:-NEoCLnf943lp-zarY_0:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/58a9462bffb73c640fd95bcbf5666a092fef881b/src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html#L14)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

As per Daniel's comment, we need to start each word with a capital letter. 
all that don't follow this need to be updated.
</blockquote></details>

Done.
___
*[`src/app/proposal/instruments/nir/nir-general-info/nir-general-info.component.ts` line 3 at r2](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEki1GdDDsml1zhTDlg:-NEoD6Qg7V_fVVP_-CiX:b-njzfzr) ([raw file](https://github.com/saltastroops/web-manager/blob/58a9462bffb73c640fd95bcbf5666a092fef881b/src/app/proposal/instruments/nir/nir-general-info/nir-general-info.component.ts#L3)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

unused import
</blockquote></details>

Removed, thanks!

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/143)* status: 28 of 30 files reviewed, 5 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html` line 10 at r3](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEopnCr0o6ARxuKPBvo:-NEowF-aE3ujguqnVWCf:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/70e68a2d0eac1850f1ac1f41286660055984d4d5/src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html#L10)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I thought would see this as well from the below comment
start each word with a capital letter
</blockquote></details>

Done.
___
*[`src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html` line 17 at r3](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEoprdx5R6akgPneJWf:-NEowFTT9V1crXOtSP_w:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/70e68a2d0eac1850f1ac1f41286660055984d4d5/src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html#L17)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this one as well
start each word with a capital letter
</blockquote></details>

Done.
___
*[`src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html` line 18 at r3](https://reviewable.io/reviews/saltastroops/web-manager/143#-NEoptXk6v65XzInIi6F:-NEowFpCExiOGr-DwB1a:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/70e68a2d0eac1850f1ac1f41286660055984d4d5/src/app/proposal/instruments/nir/nir-dither-steps/nir-dither-steps.component.html#L18)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this one as well
start each word with a capital letter
</blockquote></details>

Done.

**Review by Eb-Zeero — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/143)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
