### PR TITLE
block-links-in-executed-observations-fix

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Block links in summary of executed observations

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/223)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/223)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block-view/block-view.component.ts` line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager/223#-NME-_ET0TjsDAHrdoCT:-NME-_ET0TjsDAHrdoCU:b-qsbbk5) ([raw file](https://github.com/saltastroops/web-manager/blob/b455a9def3deeedaa5592d131aa65afe608c81ff/src/app/proposal/blocks/block-view/block-view.component.ts#L36)):*
> ```XML
> 
>   selectedBlocks$: Subject<BlockSummary> = new Subject();
>   selectedBlocksId$: Subject<number> = new Subject();
> ```

Why would you need this observable?
___
*[`src/app/proposal/blocks/block-view/block-view.component.ts` line 119 at r1](https://reviewable.io/reviews/saltastroops/web-manager/223#-NME04Jy50feIvvF71cG:-NME04Jy50feIvvF71cH:b-lc2463) ([raw file](https://github.com/saltastroops/web-manager/blob/b455a9def3deeedaa5592d131aa65afe608c81ff/src/app/proposal/blocks/block-view/block-view.component.ts#L119)):*
> ```XML
>           (block) => block.id === selectedBlockId,
>         );
>         if (index === -1) {
> ```

The case `index === -1` should never happen, should it?

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/223)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block-view/block-view.component.ts` line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager/223#-NME-_ET0TjsDAHrdoCT:-NME-_ET0TjsDAHrdoCU:b-qsbbk5) ([raw file](https://github.com/saltastroops/web-manager/blob/b455a9def3deeedaa5592d131aa65afe608c81ff/src/app/proposal/blocks/block-view/block-view.component.ts#L36)):*
> ```XML
> 
>   selectedBlocks$: Subject<BlockSummary> = new Subject();
>   selectedBlocksId$: Subject<number> = new Subject();
> ```

Why would you need this observable?
___
*[`src/app/proposal/blocks/block-view/block-view.component.ts` line 119 at r1](https://reviewable.io/reviews/saltastroops/web-manager/223#-NME04Jy50feIvvF71cG:-NME04Jy50feIvvF71cH:b-lc2463) ([raw file](https://github.com/saltastroops/web-manager/blob/b455a9def3deeedaa5592d131aa65afe608c81ff/src/app/proposal/blocks/block-view/block-view.component.ts#L119)):*
> ```XML
>           (block) => block.id === selectedBlockId,
>         );
>         if (index === -1) {
> ```

The case `index === -1` should never happen, should it?

**Comment by mofokeng-chaka** [comment]
>>  Why would you need this observable?
I need this observable because the block visit schema is different from the block summary schema, and as such there is an issue when the selected block from the executed observations is not in the block summary table (block belonging to a different semester). To solve this instead of using a block summary observable, it is better to use a blockId observable so that a request is done when the block belongs to a different semester.

>>> The case index `=== -1` should never happen, should it?

The case does happen when the selected block from the executed observations is not in the block summary table (block belonging to a different semester). That is why we don't update the block selection element in such a case and just use the blockId to request a block and view it.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/223)* status: 3 of 21 files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block-view/block-view.component.ts` line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager/223#-NMcWd_s-3DvB_878VZ-:-NME-_ET0TjsDAHrdoCU:b-6szes9) ([raw file](https://github.com/saltastroops/web-manager/blob/b455a9def3deeedaa5592d131aa65afe608c81ff/src/app/proposal/blocks/block-view/block-view.component.ts#L36)):*
> ```XML
> 
>   selectedBlocks$: Subject<BlockSummary> = new Subject();
>   selectedBlocksId$: Subject<number> = new Subject();
> ```

Shouldn't the variable be called `selectedBlockIds`?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/223)* status: 3 of 21 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/blocks/block-view/block-view.component.ts` line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager/223#-NMcWd_s-3DvB_878VZ-:-NMm9Gc9-qoljdzTbEmt:bs0vyjw) ([raw file](https://github.com/saltastroops/web-manager/blob/b455a9def3deeedaa5592d131aa65afe608c81ff/src/app/proposal/blocks/block-view/block-view.component.ts#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't the variable be called `selectedBlockIds`?
</blockquote></details>

Probably you meant `selectedBlockId` (without an "s").

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 15 of 16 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/223)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block-view/block-view.component.ts` line 36 at r1](https://reviewable.io/reviews/saltastroops/web-manager/223#-NMcWd_s-3DvB_878VZ-:-NMnq0im2dHDjwGZ8cHW:b-q0lje9) ([raw file](https://github.com/saltastroops/web-manager/blob/b455a9def3deeedaa5592d131aa65afe608c81ff/src/app/proposal/blocks/block-view/block-view.component.ts#L36)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Probably you meant `selectedBlockId` (without an "s").
</blockquote></details>

No, I didn't. The original variable name was `selectedBlocks$` and if you want to include "id" into the name, the id should be plural, not the block.

Having said that, an observable with a singular name might be more idiomatic, so I was wrong, and your new suggestion here is correct.

**Pull request merged**
