### PR TITLE
tests-updates

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Tests updates

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: all files reviewed, 5 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`.github/workflows/test.yml` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1Jpp_3JP2gzNJVeBO:-NI1Jppa8ZMuC0uDBmSf:b-8952w0) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/.github/workflows/test.yml#L32)):*
> ```YAML
>         env:
>           CYPRESS_apiUrl: /api/
>           CYPRESS_recordHttp: '{"mockFilesDirectory":"./salt-testdata/web-manager/e2e/","mockIntercepts":true}'
> ```

Why did you drop the "Config"?
___
*[`cypress/e2e/authentication.cy.ts` line 126 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1HjWyEkjUiBob2vQo:-NI1HjWyEkjUiBob2vQp:b-h12yxl) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/cypress/e2e/authentication.cy.ts#L126)):*
> ```XML
>       LoginPage.login(USERNAME, password);
> 
>       userDetailsAreStored();
> ```

Why did you move this line? The comment 

```
// Then the authentication cookie and user details are stored
```

refers to it as well.
___
*[`cypress/e2e/proposal/block-summaries.cy.ts` line 138 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1JDA_Ey-l2vY552Vp:-NI1JDA_Ey-l2vY552Vq:b-em8suw) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/cypress/e2e/proposal/block-summaries.cy.ts#L138)):*
> ```XML
> 
>   it("should load the correct block content when a block name link is clicked", () => {
>     BlockSummaries.clickBlockNameLink(1);
> ```

Choosing 1 here is probably not ideal -- you are testing that the clicked block is shown; but the first block might ve shown by default already, so that yiu are testing nothing, really.
___
*[`cypress/support/utils.ts` line 85 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1KakOAOxq44lvlYI9:-NI1KakOAOxq44lvlYIA:b-8rc3sm) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/cypress/support/utils.ts#L85)):*
> ```XML
>   cy.task("updateUserPassword", username).then((password: string) => {
>     return cy.request({
>       url: "http://127.0.0.1:8001/token",
> ```

Shouldn't you rather call the login endpoint here? (Is this function actually still used?)
___
*[`cypress/support/pages/login/login-page.ts` line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1ID-0-bUfGdZYxzV8:-NI1ID-1Cv_W1Kf83h0t:bno0flm) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/cypress/support/pages/login/login-page.ts#L44)):*
> ```XML
>   static logout() {
>     cy.get('[data-test="logout"]').click();
>     cy.clearCookie("secondary_auth_token");
> ```

I don't think you should have to clear the cookie -- this is something the tested app should do the you make the click in the previous line.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: 2 of 14 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[`.github/workflows/test.yml` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1Jpp_3JP2gzNJVeBO:-NI7k8p8-Mbsw1fgwduE:bhraqk3) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/.github/workflows/test.yml#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you drop the "Config"?
</blockquote></details>

It is because in the error message we mention recordHttp. I have changed this to include it again.
___
*[`cypress/e2e/authentication.cy.ts` line 126 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1HjWyEkjUiBob2vQo:-NI7qY5EEhl6gwiIrKM9:b54pbtg) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/cypress/e2e/authentication.cy.ts#L126)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you move this line? The comment 

```
// Then the authentication cookie and user details are stored
```

refers to it as well.
</blockquote></details>

I think the test was failing and after I moved this line it passed. I moved it back now.
___
*[`cypress/support/utils.ts` line 85 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1KakOAOxq44lvlYI9:-NI7eAwnBQysTier8y7b:bqcs26u) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/cypress/support/utils.ts#L85)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't you rather call the login endpoint here? (Is this function actually still used?)
</blockquote></details>

This function is no longer needed.
___
*[`cypress/support/pages/login/login-page.ts` line 44 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1ID-0-bUfGdZYxzV8:-NI7e6oN24Xz3OXlY3d3:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/cypress/support/pages/login/login-page.ts#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you should have to clear the cookie -- this is something the tested app should do the you make the click in the previous line.
</blockquote></details>

Done.
___
*[`cypress/e2e/proposal/block-summaries.cy.ts` line 138 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1JDA_Ey-l2vY552Vp:-NI7eh8V1wM7w6vKqQ7W:b-9kwecg) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/cypress/e2e/proposal/block-summaries.cy.ts#L138)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Choosing 1 here is probably not ideal -- you are testing that the clicked block is shown; but the first block might ve shown by default already, so that yiu are testing nothing, really.
</blockquote></details>

That is true. The reason for this is the fact that i used a different proposal that has only 2 blocks, which is something i did for the block summarires table. Anyway, i have changed this back to the previous proposal code and clicked the fourth block.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: all files reviewed, 3 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`.github/workflows/test.yml` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1Jpp_3JP2gzNJVeBO:-NI889RgAhbvnjsbNWLl:bnguqx) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/.github/workflows/test.yml#L32)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

It is because in the error message we mention recordHttp. I have changed this to include it again.
</blockquote></details>

Good point. But then iy=t might be worth correcting the error message...
___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 35 at r2](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI88l7T30uFfJBx0I2p:-NI88l7T30uFfJBx0I2q:bgwypl6) ([raw file](https://github.com/saltastroops/web-manager/blob/dabb39970f37e06124b414555b4036144db1a113/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L35)):*
> ```XML
> 
>   it("should load the correct block content when a block name link is clicked", () => {
>     SummaryOfExecutedObservations.clickBlockNameLink(1);
> ```

Why did you change this? 8 is more meaningful than 1 -- there first block might be selected already before the link is clicked.
___
*[`cypress/support/commands.ts` line 43 at r2](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI897FvC5aegLlF1WlQ:-NI897FvC5aegLlF1WlR:bkoty1n) ([raw file](https://github.com/saltastroops/web-manager/blob/dabb39970f37e06124b414555b4036144db1a113/cypress/support/commands.ts#L43)):*
> ```XML
>       const date = new Date();
>       if ("set-cookie" in response.headers) {
>         response.headers["set-cookie"] = response.headers["set-cookie"][0];
> ```

This seems dangerous to me, given there is no guarantee that the first token is the correct one.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`.github/workflows/test.yml` line 32 at r1](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI1Jpp_3JP2gzNJVeBO:-NI8WfwTA8YTSbsrKHvM:b-tqjop6) ([raw file](https://github.com/saltastroops/web-manager/blob/79dd1a8b0e385235655e02521b089b02cff7278c/.github/workflows/test.yml#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Good point. But then iy=t might be worth correcting the error message...
</blockquote></details>

I did already, in the `cypress/support/e2e.ts` file.
___
*[`cypress/e2e/proposal/summary-of-executed-observations.cy.ts` line 35 at r2](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI88l7T30uFfJBx0I2p:-NI8X1-aBCP96X4iHJoF:b-fjpces) ([raw file](https://github.com/saltastroops/web-manager/blob/dabb39970f37e06124b414555b4036144db1a113/cypress/e2e/proposal/summary-of-executed-observations.cy.ts#L35)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why did you change this? 8 is more meaningful than 1 -- there first block might be selected already before the link is clicked.
</blockquote></details>

This has to do with the fact that there is no guarantee that the 8th block in the summary of executed observations is for that specific semester. I will be addressing this issue in the other PR i am working on.
___
*[`cypress/support/commands.ts` line 43 at r2](https://reviewable.io/reviews/saltastroops/web-manager/193#-NI897FvC5aegLlF1WlQ:-NIAhiW74sDjFX67Nfby:b-y0snf9) ([raw file](https://github.com/saltastroops/web-manager/blob/dabb39970f37e06124b414555b4036144db1a113/cypress/support/commands.ts#L43)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This seems dangerous to me, given there is no guarantee that the first token is the correct one.
</blockquote></details>

I have changed this logic. It appears that two cookies are only included in the header when the user first logs in, for any other request, only a session cookie is included. So I have handled this accordingly.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: 19 of 24 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`.eslintrc.json` line 3 at r4](https://reviewable.io/reviews/saltastroops/web-manager/193#-NICPYvbCquRuNm7Pdcj:-NIDtFwRBIShmJJB_OA9:bgvjcql) ([raw file](https://github.com/saltastroops/web-manager/blob/14428bc7fddf6cb5b7d1bc35badf850f5cfd1c2b/.eslintrc.json#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that the location of `salt-testdata` is user-specific (I don't even have it in the project folder), maybe allow an arbritrary directory (`**/salt-testdata`)?

Also, isn't there duplicate information in `.eslintignore` and `.eslintrc.json` now?
</blockquote></details>

I have removed duplicate information now.
___
*[`cypress/e2e/forgot-password.cy.ts` line 86 at r4](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIDCqQwDWou2ShRMjtO:-NIDar2834BmAzLE-kl9:bulbq8y) ([raw file](https://github.com/saltastroops/web-manager/blob/14428bc7fddf6cb5b7d1bc35badf850f5cfd1c2b/cypress/e2e/forgot-password.cy.ts#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you enforce types, I'd suggest to do it properly and define a type for emails. This probably would be something like

```
interface Email {
  to: string;
  body: string;
  html;
}
```

This should enable you to get rid of all these `eslint-disable-next-line`, as yiou can replace `any` with `Email`.
</blockquote></details>

The first type i was able to change without an issue, the other two i am getting an error about incompatible type. 
___
*[`cypress/support/commands.ts` line 46 at r3](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIBe6BmBabdEV4dSxq6:-NIDR21o1_YKY2zSYM2D:b-t19oy3) ([raw file](https://github.com/saltastroops/web-manager/blob/411c959e50556c8d773ebfd003c2b43813633af8/cypress/support/commands.ts#L46)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to consistently ignore all cookies other than the secondary_auth_token one. (It might be worth having a log message with a warning about this as well.) Something like this:

```
// There can be a session and a secondary auth toke cooke. However, Cypress can
// handle a single cookie only. We thus discard the session cookie, which is not
// needed when mocking.
if ("set-cookie" in response.headers) {
  const cookies = response.headers["set-cookie"])
  if (cookies.length > 1) {
    console.warn("One or more cookies are ignored.");
  }
  for (const cookie of cookies {
    if (cookie.startsWith("secondary_auth_token=")) {
      response.headers["set-cookie"] = cookie;
      break;
    }    
  }
}
```
   
</blockquote></details>

There is one proble with the above approach, the session cookie does pass to the response because it is not handled properly. Following the log message and the comment, I have added an else statement to discard the session cookie by deleting the cookie headers.

It took me some couple debugging and fixing errors to see that `response.headers["set-cookie"]` is an object with keys 0 and 1, with cookies as values.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: all files reviewed, 5 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`.eslintrc.json` line 3 at r4](https://reviewable.io/reviews/saltastroops/web-manager/193#-NICPYvbCquRuNm7Pdcj:-NIHJcPS0qD8BI6fWPiB:b-agojxw) ([raw file](https://github.com/saltastroops/web-manager/blob/14428bc7fddf6cb5b7d1bc35badf850f5cfd1c2b/.eslintrc.json#L3)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

I have removed duplicate information now.
</blockquote></details>

Another thought... Give that salt-testdata is another repo, the directory should not be in this repo. So I guess it should be removed from the list of ignored patterns again?
___
*[`cypress/e2e/forgot-password.cy.ts` line 86 at r4](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIDCqQwDWou2ShRMjtO:-NIHP41D3vXyI67jXcO-:bb10e15) ([raw file](https://github.com/saltastroops/web-manager/blob/14428bc7fddf6cb5b7d1bc35badf850f5cfd1c2b/cypress/e2e/forgot-password.cy.ts#L86)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

The first type i was able to change without an issue, the other two i am getting an error about incompatible type. 
</blockquote></details>

And the error suggests there might be a real problem. Given the code is working (and I have raised an issue on GitHub), I guess this PR can live with the errors (or rather with the ignore comments suppressing the errors).
___
*[`cypress/support/commands.ts` line 49 at r6](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIHRTzH1jg68aiK7IAA:-NIHRTzI7ps3YqdvI5V-:bnlgjuf) ([raw file](https://github.com/saltastroops/web-manager/blob/bef38fa30cd11bc01a94abc901e2f223d9d5b170/cypress/support/commands.ts#L49)):*
> ```XML
>           console.warn("One or more cookies are ignored.");
>         }
>         for (const [, cookie] of cookies.entries()) {
> ```

Is `cookies` really not an array?
___
*[`cypress/support/commands.ts` line 57 at r6](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIHRl6Z9SDgYL-UHHPq:-NIHRl6Z9SDgYL-UHHPr:byj3jm8) ([raw file](https://github.com/saltastroops/web-manager/blob/bef38fa30cd11bc01a94abc901e2f223d9d5b170/cypress/support/commands.ts#L57)):*
> ```XML
>             break;
>           } else {
>             delete response.headers["set-cookie"];
> ```

I'mnot convinced deleting the set-cookie header ,multiple times is a good idea.
___
*[`cypress/support/types.ts` line 10 at r6](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIHRxqG9PH4UfanNIZ7:-NIHRxqG9PH4UfanNIZ8:bo0k0n6) ([raw file](https://github.com/saltastroops/web-manager/blob/bef38fa30cd11bc01a94abc901e2f223d9d5b170/cypress/support/types.ts#L10)):*
> ```XML
>   to: string;
>   body: string;
>   html;
> ```

Isn't there a type missing for `html`?

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: 21 of 24 files reviewed, 5 unresolved discussions (waiting on @hettlage)

___
*[`.eslintrc.json` line 3 at r4](https://reviewable.io/reviews/saltastroops/web-manager/193#-NICPYvbCquRuNm7Pdcj:-NIHmoB57vhD-AN1RxB0:b-pbdqz3) ([raw file](https://github.com/saltastroops/web-manager/blob/14428bc7fddf6cb5b7d1bc35badf850f5cfd1c2b/.eslintrc.json#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Another thought... Give that salt-testdata is another repo, the directory should not be in this repo. So I guess it should be removed from the list of ignored patterns again?
</blockquote></details>

Agreed.
___
*[`cypress/e2e/forgot-password.cy.ts` line 86 at r4](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIDCqQwDWou2ShRMjtO:-NIHsGgs6Za_FKNy3E3Z:b-ompgh3) ([raw file](https://github.com/saltastroops/web-manager/blob/14428bc7fddf6cb5b7d1bc35badf850f5cfd1c2b/cypress/e2e/forgot-password.cy.ts#L86)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

And the error suggests there might be a real problem. Given the code is working (and I have raised an issue on GitHub), I guess this PR can live with the errors (or rather with the ignore comments suppressing the errors).
</blockquote></details>

I agree with you.
___
*[`cypress/support/commands.ts` line 49 at r6](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIHRTzH1jg68aiK7IAA:-NIHn_36E5AOuKRd8efX:bz0rznu) ([raw file](https://github.com/saltastroops/web-manager/blob/bef38fa30cd11bc01a94abc901e2f223d9d5b170/cypress/support/commands.ts#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is `cookies` really not an array?
</blockquote></details>

In principle it is. However, in this case it "behaves" like an object.
___
*[`cypress/support/commands.ts` line 57 at r6](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIHRl6Z9SDgYL-UHHPq:-NIHoEh60Cg_pZqiK9eM:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/bef38fa30cd11bc01a94abc901e2f223d9d5b170/cypress/support/commands.ts#L57)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'mnot convinced deleting the set-cookie header ,multiple times is a good idea.
</blockquote></details>

Done.
___
*[`cypress/support/types.ts` line 10 at r6](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIHRxqG9PH4UfanNIZ7:-NIHs2acAchhOFy0Hx6F:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/bef38fa30cd11bc01a94abc901e2f223d9d5b170/cypress/support/types.ts#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't there a type missing for `html`?
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`cypress/support/commands.ts` line 49 at r7](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIHtclv3F-TwGq-sD_x:-NIHtclw616QXY4sUyLY:bjod0vk) ([raw file](https://github.com/saltastroops/web-manager/blob/6d70600f966af785803f9e228a43cba0028faef1/cypress/support/commands.ts#L49)):*
> ```XML
>           console.warn("One or more cookies are ignored.");
>         }
>         let secondaryCookieExist = false;
> ```

Exist > Exists

BTW, you could do without this variable, I think:

```
const cookieEntries = cookies.entries();
delete response.headers["set-cookie"];
 for (const [, cookie] of cookieEntries) {
          if (cookie.includes("secondary_auth_token=")) {
            secondaryCookieExist = true;
            response.headers["set-cookie"] = cookie;
            break;
          }
}
```

Also note the "=" after secondary_auth_token -- this handles the (somewhat academic) case that there is a cookie like "secondary_auth_token_foo".

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`cypress/support/commands.ts` line 49 at r7](https://reviewable.io/reviews/saltastroops/web-manager/193#-NIHtclv3F-TwGq-sD_x:-NIHw0mg3eGmuo1ZDvwk:beu5al3) ([raw file](https://github.com/saltastroops/web-manager/blob/6d70600f966af785803f9e228a43cba0028faef1/cypress/support/commands.ts#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Exist > Exists

BTW, you could do without this variable, I think:

```
const cookieEntries = cookies.entries();
delete response.headers["set-cookie"];
 for (const [, cookie] of cookieEntries) {
          if (cookie.includes("secondary_auth_token=")) {
            secondaryCookieExist = true;
            response.headers["set-cookie"] = cookie;
            break;
          }
}
```

Also note the "=" after secondary_auth_token -- this handles the (somewhat academic) case that there is a cookie like "secondary_auth_token_foo".
</blockquote></details>

Thanks! I have added this update.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/193)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
