### PR TITLE
latest-block-submission-date

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Add the latest block submission date

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/303)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/303)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block/block.component.html` line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager/303#-NOy3ThZ8ClEobNi91J3:-NOy3ThZ8ClEobNi91J4:b-czq5x1) ([raw file](https://github.com/saltastroops/web-manager/blob/754999f643462d1524b20bc777c06ca12e309fb2/src/app/proposal/blocks/block/block.component.html#L18)):*
> ```HTML
>       [comment]="block.comment"
>       [priority]="block.priority"
>       [latestSubmissionDate]="block.latestSubmissionDate"
> ```

Given that now you are passing three properties of `block`, maybe you should rather pass the `block` itself?
___
*[`src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts` line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager/303#-NOy3wwP7Te1UXn3v-oi:-NOy2vfY2I8q2kJuLSMN:b-j2oiex) ([raw file](https://github.com/saltastroops/web-manager/blob/754999f643462d1524b20bc777c06ca12e309fb2/src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts#L15)):*
> ```XML
>   @Input() latestSubmissionDate!: string;
> 
>   parseDate(date: string): Date {
> ```

(Alternatively you could parse the date in the `ngOnInit` method.)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/303)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/blocks/block/block.component.html` line 18 at r1](https://reviewable.io/reviews/saltastroops/web-manager/303#-NOy3ThZ8ClEobNi91J3:-NOy7eSZ-XrFFCrgD0Lx:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/754999f643462d1524b20bc777c06ca12e309fb2/src/app/proposal/blocks/block/block.component.html#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that now you are passing three properties of `block`, maybe you should rather pass the `block` itself?
</blockquote></details>

Done.
___
*[`src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts` line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager/303#-NOy3wwP7Te1UXn3v-oi:-NOy7fLZ-HsL1YM0-qcL:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/754999f643462d1524b20bc777c06ca12e309fb2/src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

(Alternatively you could parse the date in the `ngOnInit` method.)
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/303)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts` line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager/303#-NOy3wwP7Te1UXn3v-oi:-NPGq8VAE1UBvu6b-tol:bxyb3fa) ([raw file](https://github.com/saltastroops/web-manager/blob/754999f643462d1524b20bc777c06ca12e309fb2/src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts#L15)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And I guess you could remove the `parseDate` method now?

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/303)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts` line 15 at r1](https://reviewable.io/reviews/saltastroops/web-manager/303#-NOy3wwP7Te1UXn3v-oi:-NPGq8VAE1UBvu6b-tol:bxyb3fa) ([raw file](https://github.com/saltastroops/web-manager/blob/754999f643462d1524b20bc777c06ca12e309fb2/src/app/proposal/blocks/block/priority-comment/priority-comment.component.ts#L15)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And I guess you could remove the `parseDate` method now?

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/303)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
