### PR TITLE
Progress update

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/141)

### CODE REVIEW

**Comment by hettlage** [comment]
I've found some issues:

* There is no "wait indicator" when you submit the proposal progress, and no success indicator either.
* Not all the proposal progress details are shown when an existing progress report is edited.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 23 of 24 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/141)* status: all files reviewed, 4 unresolved discussions (waiting on @Eb-Zeero)

___
*[`tsconfig.json` line 18 at r2](https://reviewable.io/reviews/saltastroops/web-manager/141#-NEkoBoEBHbDGCcDVZ8u:-NEkoBoEBHbDGCcDVZ8v:b-5xk1ht) ([raw file](https://github.com/saltastroops/web-manager/blob/ca7e9a3f311bca0e97d2681ff288d6c6cb5067ad/tsconfig.json#L18)):*
> ```jsonc
>     "moduleResolution": "node",
>     "importHelpers": true,
>     "target": "es2020",
> ```

Is this change necessary?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 83 at r2](https://reviewable.io/reviews/saltastroops/web-manager/141#-NEkpd405rsBbIp59zlq:-NEkpd405rsBbIp59zlr:bv6ctot) ([raw file](https://github.com/saltastroops/web-manager/blob/ca7e9a3f311bca0e97d2681ff288d6c6cb5067ad/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L83)):*
> ```HTML
>                 }"
>               />
>               <input hidden formControlName="requestedPercentage" [value]="t.value.partnerName">
> ```

This looks odd... Why is the control name "requestedPercentage", but the value a partner name?
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 197 at r2](https://reviewable.io/reviews/saltastroops/web-manager/141#-NEkqsKK6ZfLTBPM1RFn:-NEkqsKK6ZfLTBPM1RFo:b-vxmk8o) ([raw file](https://github.com/saltastroops/web-manager/blob/ca7e9a3f311bca0e97d2681ff288d6c6cb5067ad/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L197)):*
> ```XML
>   }
> 
>   validateAttachedFile(fileType: string): void {
> ```

IMHO it might make more sense to pass the file type as the argument.
___
*[`src/app/types/proposal.ts` line 157 at r2](https://reviewable.io/reviews/saltastroops/web-manager/141#-NEks83nDIix9EqElBbO:-NEks83nDIix9EqElBbP:b9o2a7z) ([raw file](https://github.com/saltastroops/web-manager/blob/ca7e9a3f311bca0e97d2681ff288d6c6cb5067ad/src/app/types/proposal.ts#L157)):*
> ```XML
>   strategyChanges: string | null;
>   previousTimeRequests: TimeStatistics[];
>   fileSource: File | null
> ```

Shouldn't this field have a more descriptive name? And it seems to be missing in the Pedantic type on the backend?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/141)* status: 24 of 26 files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`tsconfig.json` line 18 at r2](https://reviewable.io/reviews/saltastroops/web-manager/141#-NEkoBoEBHbDGCcDVZ8u:-NF9Ntnd7QzctuMa_Oog:bdllib3) ([raw file](https://github.com/saltastroops/web-manager/blob/ca7e9a3f311bca0e97d2681ff288d6c6cb5067ad/tsconfig.json#L18)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Is this change necessary?
</blockquote></details>

don't know how it changed
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html` line 83 at r2](https://reviewable.io/reviews/saltastroops/web-manager/141#-NEkpd405rsBbIp59zlq:-NF9PIroCse7kDnr6-rV:b-voyb5a) ([raw file](https://github.com/saltastroops/web-manager/blob/ca7e9a3f311bca0e97d2681ff288d6c6cb5067ad/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.html#L83)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This looks odd... Why is the control name "requestedPercentage", but the value a partner name?
</blockquote></details>

this should have been a lazy programming the input is always hidden
___
*[`src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts` line 197 at r2](https://reviewable.io/reviews/saltastroops/web-manager/141#-NEkqsKK6ZfLTBPM1RFn:-NF9aQiwD4zCnYpxDZKS:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/ca7e9a3f311bca0e97d2681ff288d6c6cb5067ad/src/app/proposal/general/proposal-progress/progress-request-form/progress-request-form.component.ts#L197)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

IMHO it might make more sense to pass the file type as the argument.
</blockquote></details>

Done.
___
*[`src/app/types/proposal.ts` line 157 at r2](https://reviewable.io/reviews/saltastroops/web-manager/141#-NEks83nDIix9EqElBbO:-NF9SgNADpVu_LlrkBat:b-x537eb) ([raw file](https://github.com/saltastroops/web-manager/blob/ca7e9a3f311bca0e97d2681ff288d6c6cb5067ad/src/app/types/proposal.ts#L157)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this field have a more descriptive name? And it seems to be missing in the Pedantic type on the backend?
</blockquote></details>

not even used somehow

**Review by hettlage — APPROVED** [review]
> Reviewed 2 of 2 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Review by hettlage — APPROVED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)

**Pull request merged**
