### PR TITLE
toggle-list-of-observation

### PR DESCRIPTION
**Pull request by mofokeng-chaka**
Toggle executed observations

- - -
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: all files reviewed, 4 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 6 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNak4xCCD6JRRIInjv7:-NNak4xCCD6JRRIInjv8:b-5muy09) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L6)):*
> ```HTML
> <hr class="heading-line summary-header" />
> <p class="mb-2">
>   <a
> ```

Can be simplified:

```
  <a class="has-text-link" (click)="toggleObservationsList()"
    >{{ showObservationsList ? "Hide" : "Show" }} list of observations.</a
  >
```
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 163 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNahboqCwnfCroW8beO:-NNahboqCwnfCroW8beP:b-5tjtvf) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L163)):*
> ```HTML
>       </td>
>     </tr>
>     <tr>
> ```

This should not be a table row but a paragraph below the table.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 166 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNajzrdCeOOr_apWf_M:-NNajzrdCeOOr_apWf_N:b-5muy09) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L166)):*
> ```HTML
>       <td colspan="8">
>         <p>
>           <a
> ```

Can be simplified:

```
  <a class="has-text-link" (click)="toggleObservationsList()"
    >{{ showObservationsList ? "Hide" : "Show" }} list of observations.</a
  >
```
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 96 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNahQnu1_BbjO5gF-Gp:-NNahQnu1_BbjO5gF-Gq:b-hr9sq8) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L96)):*
> ```XML
>     const element = document.getElementById("executed-observations");
>     if (!this.showObservationsList) {
>       element?.scrollIntoView();
> ```

I'm not convinced you should scroll into view. (Maybe worth a quick chat?)

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: all files reviewed, 4 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 6 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNak4xCCD6JRRIInjv7:-NNeeMnMB3sKEyxvztyA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can be simplified:

```
  <a class="has-text-link" (click)="toggleObservationsList()"
    >{{ showObservationsList ? "Hide" : "Show" }} list of observations.</a
  >
```
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 163 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNahboqCwnfCroW8beO:-NNeeeho0KVov_11-bfz:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L163)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This should not be a table row but a paragraph below the table.
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 166 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNajzrdCeOOr_apWf_M:-NNeefZ24dfPQiX7tooT:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L166)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can be simplified:

```
  <a class="has-text-link" (click)="toggleObservationsList()"
    >{{ showObservationsList ? "Hide" : "Show" }} list of observations.</a
  >
```
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 96 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNahQnu1_BbjO5gF-Gp:-NNf3VOX1m3amRz1nk8U:bwjwrd4) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm not convinced you should scroll into view. (Maybe worth a quick chat?)
</blockquote></details>

As per our discussion, it is best I leave this as is – it will be attended to if users raise some issues with it.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 158 at r2](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNg0T909EkgDXwkDYzC:-NNg0T909EkgDXwkDYzD:b-7klrz6) ([raw file](https://github.com/saltastroops/web-manager/blob/0f939afa1a5427b0c8b28aaa8d968cf9d14e447d/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L158)):*
> ```HTML
> <p *ngIf="showObservationsList">
>   <a class="has-text-link" (click)="toggleObservationsList()">
>     Hide list of observations.
> ```

This will always show "Hide"?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 96 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNahQnu1_BbjO5gF-Gp:-NNg0_9c04bcaP_e8kzr:bmsiv1y) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L96)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

As per our discussion, it is best I leave this as is – it will be attended to if users raise some issues with it.
</blockquote></details>

Didn't we say that there should be no scrolling for the link above the table?

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 158 at r2](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNg0T909EkgDXwkDYzC:-NNg0T909EkgDXwkDYzD:b-7klrz6) ([raw file](https://github.com/saltastroops/web-manager/blob/0f939afa1a5427b0c8b28aaa8d968cf9d14e447d/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L158)):*
> ```HTML
> <p *ngIf="showObservationsList">
>   <a class="has-text-link" (click)="toggleObservationsList()">
>     Hide list of observations.
> ```

This will always show "Hide"?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 96 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNahQnu1_BbjO5gF-Gp:-NNg0_9c04bcaP_e8kzr:bmsiv1y) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L96)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

As per our discussion, it is best I leave this as is – it will be attended to if users raise some issues with it.
</blockquote></details>

Didn't we say that there should be no scrolling for the link above the table?

**Comment by mofokeng-chaka** [comment]
>> This will always show "Hide"?

That's true, and since the link can only be shown when the table is shown, when the table is hidden (the link is "Show list of observations") this link is also hidden. Therefore, the link is only shown when it is "Hide list of observations"

>> Didn't we say that there should be no scrolling for the link above the table?

My mistake i forgot to add a separate function without the scrolling. It is done now.

**Review by hettlage — CHANGES_REQUESTED** [review]
I'd suggest you use a single function toggleObservationsList and use an argument to decide whether to scroll.

> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282#-:-NNgFiP2Cpj1HtMa_o74:b-8fljxt)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

**Review by mofokeng-chaka — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282#-:-NNg_9KT4ZDgX1ym9p7u:bb6un1j)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 158 at r2](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNg0T909EkgDXwkDYzC:-NNg_4FO58lGZybMW8np:bho3bry) ([raw file](https://github.com/saltastroops/web-manager/blob/0f939afa1a5427b0c8b28aaa8d968cf9d14e447d/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L158)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This will always show "Hide"?
</blockquote></details>

That's true, and since the link can only be shown when the table is shown, when the table is hidden (the link is "Show list of observations") this link is also hidden. Therefore, the link is only shown when it is "Hide list of observations"
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 96 at r1](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNahQnu1_BbjO5gF-Gp:-NNg_8Nz1Y7m2y6kzGTy:behaqb2) ([raw file](https://github.com/saltastroops/web-manager/blob/fd54238211d39fd743dd490ecd8db8cfa9fa9949/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L96)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Didn't we say that there should be no scrolling for the link above the table?
</blockquote></details>

My mistake i forgot to add a separate function without the scrolling. It is done now.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: all files reviewed, 2 unresolved discussions (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 158 at r2](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNg0T909EkgDXwkDYzC:-NNkjczh8wCMMAfJEHq1:btbyrtb) ([raw file](https://github.com/saltastroops/web-manager/blob/0f939afa1a5427b0c8b28aaa8d968cf9d14e447d/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L158)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

That's true, and since the link can only be shown when the table is shown, when the table is hidden (the link is "Show list of observations") this link is also hidden. Therefore, the link is only shown when it is "Hide list of observations"
</blockquote></details>

Ahhh, my bad. Obviously you only want one link if the table isn't visible.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 92 at r4](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNkkYrn47pK2Urr85zr:-NNkkYrn47pK2Urr85zs:b-qknzxz) ([raw file](https://github.com/saltastroops/web-manager/blob/842e628e8f53a75f4cbca864b17851b23c68d8da/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L92)):*
> ```XML
>   }
> 
>   toggleObservationsList(scrollToList: boolean): void {
> ```

Isn't this more something like `ScrollToSection`, given the list itself is hidden?
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 94 at r4](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNkjy-M8WePqeHkGYxw:-NNkjy-M8WePqeHkGYxx:bp7yx89) ([raw file](https://github.com/saltastroops/web-manager/blob/842e628e8f53a75f4cbca864b17851b23c68d8da/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L94)):*
> ```XML
>   toggleObservationsList(scrollToList: boolean): void {
>     this.showObservationsList = !this.showObservationsList;
>     const element = document.getElementById("executed-observations");
> ```

Arguably it might have made more sense to move the definition of element inside the if block as well. But I'll accept the PR with or without this change.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 92 at r4](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNkkYrn47pK2Urr85zr:-NNp7eRsCJ-TI6ZKkC9S:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/842e628e8f53a75f4cbca864b17851b23c68d8da/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L92)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't this more something like `ScrollToSection`, given the list itself is hidden?
</blockquote></details>

Done.
___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 94 at r4](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNkjy-M8WePqeHkGYxw:-NNp7g6c-TIfJaBRAZWr:b8pntxf) ([raw file](https://github.com/saltastroops/web-manager/blob/842e628e8f53a75f4cbca864b17851b23c68d8da/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L94)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Arguably it might have made more sense to move the definition of element inside the if block as well. But I'll accept the PR with or without this change.
</blockquote></details>

I have added this update as well.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @hettlage)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html` line 158 at r2](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNg0T909EkgDXwkDYzC:-NNp7srL4BStrsvCYbOA:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/0f939afa1a5427b0c8b28aaa8d968cf9d14e447d/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.html#L158)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ahhh, my bad. Obviously you only want one link if the table isn't visible.
</blockquote></details>

Done.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: all files reviewed, 1 unresolved discussion (waiting on @mofokeng-chaka)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 92 at r4](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNkkYrn47pK2Urr85zr:-NNqmj-j2clbRudo9yOP:bv5bma5) ([raw file](https://github.com/saltastroops/web-manager/blob/842e628e8f53a75f4cbca864b17851b23c68d8da/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L92)):*
<details><summary><i>Previously, mofokeng-chaka (Chaka Mofokeng) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oh, sorry, the capital 'S' was a typo of course; it should have been `scrollToSection`.

**Review by mofokeng-chaka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts` line 92 at r4](https://reviewable.io/reviews/saltastroops/web-manager/282#-NNkkYrn47pK2Urr85zr:-NNtbZrd3ItMwxMmmmiv:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/842e628e8f53a75f4cbca864b17851b23c68d8da/src/app/proposal/general/summary-of-executed-observations/summary-of-executed-observations.component.ts#L92)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Oh, sorry, the capital 'S' was a typo of course; it should have been `scrollToSection`.
</blockquote></details>

Done.

**Review by hettlage — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Review by hettlage — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mofokeng-chaka)

**Pull request merged**
