### PR TITLE
Creating a phase one proposal

### PR DESCRIPTION
**Pull request by Eb-Zeero**
This change is [Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/208)

### CODE REVIEW

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 49 of 49 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/208)* status: all files reviewed, 14 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/proposal.component.html` line 67 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTbCJC91mJxDzFqKcF:-NMTbCJDE2ugMUUOcLAg:b-pk4zq) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/proposal.component.html#L67)):*
> ```HTML
>   </ng-template>
>   <ng-template #phase1>
>     <wm-phase-one [proposal]="proposal"></wm-phase-one>
> ```

If you have a component for Phase 1, you should consider moving the Phase 2 content into its own component as well.

Also, maybe call the component "phase-one-details" or perhaps better "p1-details" or "phase1-details"?

I've raised an issue for this.
___
*[`src/app/proposal/general/proposal-details/details-table/details-table.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTci874UrdgVF56coT:-NMTci874UrdgVF56coU:b-ixspv1) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/general/proposal-details/details-table/details-table.component.html#L1)):*
> ```HTML
> <div>
> ```

"details-table" is a too generic name. (Although it is hard to think of any reasonable name...)

I've raised an issue for this.
___
*[`src/app/proposal/general/proposal-details/proposal-download/proposal-download.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTdBa4CtSQ7sAem4Fj:-NMTdBa4CtSQ7sAem4Fk:b-sgsgmt) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/general/proposal-details/proposal-download/proposal-download.component.html#L1)):*
> ```HTML
> <div>
> ```

The name "proposal-download" is a bit misleading -- you wouldn't expect the proposal liaison to be included in this component.

I've raised an issue for this.
___
*[`src/app/proposal/general/proposal-details/proposal-summary/proposal-summary.component.html` line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTdmCmBncvGNNCL6N4:-NMTdmCmBncvGNNCL6N5:bvar8po) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/general/proposal-details/proposal-summary/proposal-summary.component.html#L8)):*
> ```HTML
>     <tr>
>       <td>
>         <div class="notificati">
> ```

Shouldn't that read `notification`?
___
*[`src/app/proposal/phase-one/phase-one.component.html` line 19 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTeK6_CD-mmn3QZefu:-NMTeK6_CD-mmn3QZefv:b-twuc20) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/phase-one/phase-one.component.html#L19)):*
> ```HTML
> </div>
> <div class="block">
>   <wm-phase-one-target [phase1Targets]="proposal.targets"></wm-phase-one-target>
> ```

Maybe better "phase1-targets" or "p1-targets"?

Why don't you just call the attribute `targets`?

Actually, it's probably "observations" rather than "targets".

I've raised an issue for this.
___
*[`src/app/proposal/phase-one/phase-one.component.html` line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTen_H3iObLeZEkrWV:-NMTen_H3iObLeZEkrWW:bo3amm9) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/phase-one/phase-one.component.html#L22)):*
> ```HTML
> </div>
> <div class="block">
>   <wm-phase-one-configurations [configurations]="proposal.configurations"></wm-phase-one-configurations>
> ```

Maybe better "phase1-configurations" or "p1-configurations".

I've raised an issue for this.
___
*[`src/app/proposal/phase-one/phase-one-configurations/phase-one-configurations.component.html` line 27 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTfCyv4a7N1DPgwlbo:-NMTfCyv4a7N1DPgwlbp:bexo8a1) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/phase-one/phase-one-configurations/phase-one-configurations.component.html#L27)):*
> ```HTML
>   </tr>
>   </tbody>
> </table>
> ```

It seems the details for the configurations are missing? (If you look at the old WM, there is a table for every individual configuration.)

I've raised an issue for this.
___
*[`src/app/proposal/phase-one/phase-one-proposal-details/phase-one-proposal-details.component.html` line 1 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTfg_B6fD0hbyox0Mq:-NMTfg_B6fD0hbyox0Mr:bqqbq1l) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/phase-one/phase-one-proposal-details/phase-one-proposal-details.component.html#L1)):*
> ```HTML
> <div class="inline-view">
> ```

Another component name which is too generic... :(

Maybe this is a sign that there are too many components?

I've raised an issue for this.
___
*[`src/app/proposal/phase-one/phase-one-requested-time/phase-one-requested-time.component.html` line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTg-GXBjbG1WBr8UW7:-NMTg-GXBjbG1WBr8UW8:b-473j8f) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/phase-one/phase-one-requested-time/phase-one-requested-time.component.html#L2)):*
> ```HTML
> <div>
>   <table class="table">
> ```

You aren't handling the case of multiple semesters...

This makes me wonder whether the backend actually handles that case properly...

I've raised an issue for this.
___
*[`src/app/proposal/phase-one/requested-time-distribution/requested-time-distribution.component.html` line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMThPnI2qcxc-8ZqwRq:-NMThPnI2qcxc-8ZqwRr:bn6jf40) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/phase-one/requested-time-distribution/requested-time-distribution.component.html#L2)):*
> ```HTML
> <div>
>   <table class="table">
> ```

This should be grouped with the time request table (as it is in the old WM), as it makes more sense if there are multiple semesters.

I've raised an issue for this.
___
*[`src/app/types/proposal.ts` line 63 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMThkym17JvO6-z424d:-NMThkym17JvO6-z424e:bv8zdf4) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/types/proposal.ts#L63)):*
> ```XML
> }
> 
> export interface Configuration {
> ```

"Configuration" is a too generic name.
___
*[`src/app/types/proposal.ts` line 64 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTi-Oe6dn0s63JPfUf:-NMTi-Oe6dn0s63JPfUg:bilozmp) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/types/proposal.ts#L64)):*
> ```XML
> 
> export interface Configuration {
>   observationId: number;
> ```

I'm not sure there is much value including this id?

I've raised an issue for this.
___
*[`src/app/types/proposal.ts` line 70 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTrl5q57sLkJ77hkLg:-NMTrl5q57sLkJ77hkLh:b-xbzmy1) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/types/proposal.ts#L70)):*
> ```XML
> }
> 
> export interface Proposal {
> ```

Looking at the content, I think there has to be a separate interface for Phase 1 and Phase 2.

Also, the Phase1Targets are really Phase1Observations (which then contain a Target).

I raised an issue for this.
___
*[`src/app/types/proposal.ts` line 133 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTsqdB4butEAdDSabB:-NMTsqdB4butEAdDSabC:b-jnb4w6) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/types/proposal.ts#L133)):*
> ```XML
>   comment: string | null;
>   semester: string;
>   distributions: Array<{ partner: PartnerName; percentage: number }>;
> ```

I think `distribution` was correct -- it is a single distribution of times amongst partners.

**Review by hettlage — CHANGES_REQUESTED** [review]
> Reviewed 41 of 41 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/208)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/types/target.ts` line 17 at r2](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMXl_5tE_HliQb_m05X:-NMXl_5u49N4M9643vmq:bb3r547) ([raw file](https://github.com/saltastroops/web-manager/blob/a1c45d751c4ebf359b3735a0d1f9beb83d85b80f/src/app/types/target.ts#L17)):*
> ```XML
> 
> export interface Phase1Target extends Target {
>   requestedTime: number;
> ```

No, I think this should be `observingTime`.

**Review by hettlage — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/208)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/app/proposal/p1-details/phase-one-target/phase-one-target.component.html` line 23 at r2](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMXsbn-C5JzrGHqzoz4:-NMXsbn-C5JzrGHqzoz5:boch1k9) ([raw file](https://github.com/saltastroops/web-manager/blob/a1c45d751c4ebf359b3735a0d1f9beb83d85b80f/src/app/proposal/p1-details/phase-one-target/phase-one-target.component.html#L23)):*
> ```HTML
>     <th>Optional</th>
>     <th>Visits</th>
> <th>Observing Time</th>
> ```

Why is there a TODO here?

**Review by Eb-Zeero — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/208)* status: 55 of 57 files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[`src/app/proposal/proposal.component.html` line 67 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTbCJC91mJxDzFqKcF:-NMU-D8eCFnVo5tF7P66:bfrke37) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/proposal.component.html#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If you have a component for Phase 1, you should consider moving the Phase 2 content into its own component as well.

Also, maybe call the component "phase-one-details" or perhaps better "p1-details" or "phase1-details"?

I've raised an issue for this.
</blockquote></details>

renamed will add p2-details on issue
___
*[`src/app/proposal/general/proposal-details/proposal-summary/proposal-summary.component.html` line 8 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTdmCmBncvGNNCL6N4:-NMTybDjBLNNKVsu8noH:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/general/proposal-details/proposal-summary/proposal-summary.component.html#L8)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't that read `notification`?
</blockquote></details>

Done.
___
*[`src/app/types/proposal.ts` line 63 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMThkym17JvO6-z424d:-NMU774Q-osnLomdbetn:b-z5wbhz) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/types/proposal.ts#L63)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"Configuration" is a too generic name.
</blockquote></details>

renamed to InstrumentConfiguration
___
*[`src/app/types/proposal.ts` line 133 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTsqdB4butEAdDSabB:-NMTz_ps-qNTnBMFJHH3:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/types/proposal.ts#L133)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think `distribution` was correct -- it is a single distribution of times amongst partners.
</blockquote></details>

Done.
___
*[`src/app/proposal/p1-details/phase-one-target/phase-one-target.component.html` line 23 at r2](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMXsbn-C5JzrGHqzoz4:-NMY4m870jybLesDRcM8:bqpkegf) ([raw file](https://github.com/saltastroops/web-manager/blob/a1c45d751c4ebf359b3735a0d1f9beb83d85b80f/src/app/proposal/p1-details/phase-one-target/phase-one-target.component.html#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why is there a TODO here?
</blockquote></details>

This is just what I just fixed and removed
___
*[`src/app/proposal/phase-one/phase-one.component.html` line 22 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTen_H3iObLeZEkrWV:-NMU5ICD2f1i3mJg-Cta:b-896fix) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/phase-one/phase-one.component.html#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better "phase1-configurations" or "p1-configurations".

I've raised an issue for this.
</blockquote></details>

Done.
___
*[`src/app/proposal/phase-one/phase-one-requested-time/phase-one-requested-time.component.html` line 2 at r1](https://reviewable.io/reviews/saltastroops/web-manager/208#-NMTg-GXBjbG1WBr8UW7:-NMU5gbw22nL_9P9_16M:b-ei47gu) ([raw file](https://github.com/saltastroops/web-manager/blob/ef02993f43329cb7d3773184f0dded48807ca2cc/src/app/proposal/phase-one/phase-one-requested-time/phase-one-requested-time.component.html#L2)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You aren't handling the case of multiple semesters...

This makes me wonder whether the backend actually handles that case properly...

I've raised an issue for this.
</blockquote></details>

the backend only returns data for the selected semester

**Review by hettlage — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/web-manager/208)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero)

**Pull request merged**
